// Code generated by ent, DO NOT EDIT.

package assetcategory

import (
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldID, id))
}

// CategoryName applies equality check predicate on the "category_name" field. It's identical to CategoryNameEQ.
func CategoryName(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryName, v))
}

// CategoryCode applies equality check predicate on the "category_code" field. It's identical to CategoryCodeEQ.
func CategoryCode(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryCode, v))
}

// CategoryFlag applies equality check predicate on the "category_flag" field. It's identical to CategoryFlagEQ.
func CategoryFlag(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryFlag, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// CategoryNameEQ applies the EQ predicate on the "category_name" field.
func CategoryNameEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryName, v))
}

// CategoryNameNEQ applies the NEQ predicate on the "category_name" field.
func CategoryNameNEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldCategoryName, v))
}

// CategoryNameIn applies the In predicate on the "category_name" field.
func CategoryNameIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldCategoryName, vs...))
}

// CategoryNameNotIn applies the NotIn predicate on the "category_name" field.
func CategoryNameNotIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldCategoryName, vs...))
}

// CategoryNameGT applies the GT predicate on the "category_name" field.
func CategoryNameGT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldCategoryName, v))
}

// CategoryNameGTE applies the GTE predicate on the "category_name" field.
func CategoryNameGTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldCategoryName, v))
}

// CategoryNameLT applies the LT predicate on the "category_name" field.
func CategoryNameLT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldCategoryName, v))
}

// CategoryNameLTE applies the LTE predicate on the "category_name" field.
func CategoryNameLTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldCategoryName, v))
}

// CategoryNameContains applies the Contains predicate on the "category_name" field.
func CategoryNameContains(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContains(FieldCategoryName, v))
}

// CategoryNameHasPrefix applies the HasPrefix predicate on the "category_name" field.
func CategoryNameHasPrefix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasPrefix(FieldCategoryName, v))
}

// CategoryNameHasSuffix applies the HasSuffix predicate on the "category_name" field.
func CategoryNameHasSuffix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasSuffix(FieldCategoryName, v))
}

// CategoryNameEqualFold applies the EqualFold predicate on the "category_name" field.
func CategoryNameEqualFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEqualFold(FieldCategoryName, v))
}

// CategoryNameContainsFold applies the ContainsFold predicate on the "category_name" field.
func CategoryNameContainsFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContainsFold(FieldCategoryName, v))
}

// CategoryCodeEQ applies the EQ predicate on the "category_code" field.
func CategoryCodeEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryCode, v))
}

// CategoryCodeNEQ applies the NEQ predicate on the "category_code" field.
func CategoryCodeNEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldCategoryCode, v))
}

// CategoryCodeIn applies the In predicate on the "category_code" field.
func CategoryCodeIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldCategoryCode, vs...))
}

// CategoryCodeNotIn applies the NotIn predicate on the "category_code" field.
func CategoryCodeNotIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldCategoryCode, vs...))
}

// CategoryCodeGT applies the GT predicate on the "category_code" field.
func CategoryCodeGT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldCategoryCode, v))
}

// CategoryCodeGTE applies the GTE predicate on the "category_code" field.
func CategoryCodeGTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldCategoryCode, v))
}

// CategoryCodeLT applies the LT predicate on the "category_code" field.
func CategoryCodeLT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldCategoryCode, v))
}

// CategoryCodeLTE applies the LTE predicate on the "category_code" field.
func CategoryCodeLTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldCategoryCode, v))
}

// CategoryCodeContains applies the Contains predicate on the "category_code" field.
func CategoryCodeContains(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContains(FieldCategoryCode, v))
}

// CategoryCodeHasPrefix applies the HasPrefix predicate on the "category_code" field.
func CategoryCodeHasPrefix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasPrefix(FieldCategoryCode, v))
}

// CategoryCodeHasSuffix applies the HasSuffix predicate on the "category_code" field.
func CategoryCodeHasSuffix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasSuffix(FieldCategoryCode, v))
}

// CategoryCodeEqualFold applies the EqualFold predicate on the "category_code" field.
func CategoryCodeEqualFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEqualFold(FieldCategoryCode, v))
}

// CategoryCodeContainsFold applies the ContainsFold predicate on the "category_code" field.
func CategoryCodeContainsFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContainsFold(FieldCategoryCode, v))
}

// CategoryFlagEQ applies the EQ predicate on the "category_flag" field.
func CategoryFlagEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCategoryFlag, v))
}

// CategoryFlagNEQ applies the NEQ predicate on the "category_flag" field.
func CategoryFlagNEQ(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldCategoryFlag, v))
}

// CategoryFlagIn applies the In predicate on the "category_flag" field.
func CategoryFlagIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldCategoryFlag, vs...))
}

// CategoryFlagNotIn applies the NotIn predicate on the "category_flag" field.
func CategoryFlagNotIn(vs ...string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldCategoryFlag, vs...))
}

// CategoryFlagGT applies the GT predicate on the "category_flag" field.
func CategoryFlagGT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldCategoryFlag, v))
}

// CategoryFlagGTE applies the GTE predicate on the "category_flag" field.
func CategoryFlagGTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldCategoryFlag, v))
}

// CategoryFlagLT applies the LT predicate on the "category_flag" field.
func CategoryFlagLT(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldCategoryFlag, v))
}

// CategoryFlagLTE applies the LTE predicate on the "category_flag" field.
func CategoryFlagLTE(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldCategoryFlag, v))
}

// CategoryFlagContains applies the Contains predicate on the "category_flag" field.
func CategoryFlagContains(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContains(FieldCategoryFlag, v))
}

// CategoryFlagHasPrefix applies the HasPrefix predicate on the "category_flag" field.
func CategoryFlagHasPrefix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasPrefix(FieldCategoryFlag, v))
}

// CategoryFlagHasSuffix applies the HasSuffix predicate on the "category_flag" field.
func CategoryFlagHasSuffix(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldHasSuffix(FieldCategoryFlag, v))
}

// CategoryFlagEqualFold applies the EqualFold predicate on the "category_flag" field.
func CategoryFlagEqualFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEqualFold(FieldCategoryFlag, v))
}

// CategoryFlagContainsFold applies the ContainsFold predicate on the "category_flag" field.
func CategoryFlagContainsFold(v string) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldContainsFold(FieldCategoryFlag, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.AssetCategory {
	return predicate.AssetCategory(sql.FieldNotNull(FieldUpdatedAt))
}

// HasAssetType applies the HasEdge predicate on the "asset_type" edge.
func HasAssetType() predicate.AssetCategory {
	return predicate.AssetCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetTypeTable, AssetTypeColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetType
		step.Edge.Schema = schemaConfig.AssetType
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetTypeWith applies the HasEdge predicate on the "asset_type" edge with a given conditions (other predicates).
func HasAssetTypeWith(preds ...predicate.AssetType) predicate.AssetCategory {
	return predicate.AssetCategory(func(s *sql.Selector) {
		step := newAssetTypeStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetType
		step.Edge.Schema = schemaConfig.AssetType
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAsset applies the HasEdge predicate on the "asset" edge.
func HasAsset() predicate.AssetCategory {
	return predicate.AssetCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetTable, AssetColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Assets
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Assets) predicate.AssetCategory {
	return predicate.AssetCategory(func(s *sql.Selector) {
		step := newAssetStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Assets
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AssetCategory) predicate.AssetCategory {
	return predicate.AssetCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AssetCategory) predicate.AssetCategory {
	return predicate.AssetCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AssetCategory) predicate.AssetCategory {
	return predicate.AssetCategory(sql.NotPredicates(p))
}
