package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"moon/ent"
	"moon/ent/user"
	"moon/pkg/auth"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	// 根据邮箱查询用户
	u, err := r.Client.User.Query().Where(user.Email(email)).Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return "", fmt.Errorf("用户不存在")
		}
		return "", fmt.Errorf("查询用户失败: %w", err)
	}

	// 验证密码
	if u.PasswordHash != password {
		return "", fmt.Errorf("密码错误")
	}

	organization_id := u.OrganizationID

	if organization_id == nil || *organization_id == uuid.Nil {
		return "", fmt.Errorf("获取用户组织失败: 组织ID为空")
	}

	// 获取用户的所有权限
	permissions, err := u.QueryRole().QueryPermission().All(ctx)
	if err != nil {
		return "", fmt.Errorf("获取用户权限失败: %w", err)
	}

	// 提取权限名称列表
	permissionNames := make([]string, len(permissions))
	for i, perm := range permissions {
		permissionNames[i] = perm.PermissionCode
	}

	// 生成JWT token
	token, err := auth.GenerateToken(u.ID, *organization_id, permissionNames)

	// 生成JWT token
	if err != nil {
		return "", fmt.Errorf("生成token失败: %w", err)
	}

	return token, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (string, error) {
	u, err := r.Client.User.Create().SetEmail(email).SetPasswordHash(password).SetOrganizationID(uuid.Nil).Save(ctx)
	if err != nil {
		return "", fmt.Errorf("创建用户失败: %w", err)
	}
	token, err := auth.GenerateToken(u.ID, uuid.Nil, []string{})
	if err != nil {
		return "", fmt.Errorf("生成token失败: %w", err)
	}
	return token, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id uuid.UUID, input ent.UpdateUserInput) (*ent.User, error) {
	// 获取当前用户 claims
	claims, err := auth.GetUserClaimsFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	// 检查是否是本人
	if claims.UserID != id {
		return nil, fmt.Errorf("只能修改自己的资料")
	}

	// 查询用户是否存在
	u, err := r.Client.User.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 更新用户资料
	u, err = u.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新用户资料失败: %w", err)
	}
	return u, nil
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input ent.CreateOrganizationInput) (*ent.Organization, error) {
	// 创建组织
	org, err := r.Client.Organization.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建组织失败: %w", err)
	}
	return org, nil
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, id uuid.UUID, input ent.UpdateOrganizationInput) (*ent.Organization, error) {
	// 查询组织是否存在
	org, err := r.Client.Organization.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("组织不存在")
		}
		return nil, fmt.Errorf("查询组织失败: %w", err)
	}

	// 更新组织
	org, err = org.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新组织失败: %w", err)
	}
	return org, nil
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, id uuid.UUID) (*ent.Organization, error) {
	// 查询组织是否存在
	org, err := r.Client.Organization.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("组织不存在")
		}
		return nil, fmt.Errorf("查询组织失败: %w", err)
	}

	// 删除组织
	err = r.Client.Organization.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除组织失败: %w", err)
	}
	return org, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input ent.CreateRoleInput) (*ent.Role, error) {
	role, err := r.Client.Role.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建角色失败: %w", err)
	}
	return role, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id uuid.UUID, input ent.UpdateRoleInput) (*ent.Role, error) {
	// 查询角色是否存在
	role, err := r.Client.Role.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("角色不存在")
		}
		return nil, fmt.Errorf("查询角色失败: %w", err)
	}

	// 更新角色
	role, err = role.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新角色失败: %w", err)
	}
	return role, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id uuid.UUID) (*ent.Role, error) {
	// 查询角色是否存在
	role, err := r.Client.Role.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("角色不存在")
		}
		return nil, fmt.Errorf("查询角色失败: %w", err)
	}

	// 删除角色
	err = r.Client.Role.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除角色失败: %w", err)
	}
	return role, nil
}

// CreatePermission is the resolver for the createPermission field.
func (r *mutationResolver) CreatePermission(ctx context.Context, input ent.CreatePermissionInput) (*ent.Permission, error) {
	permission, err := r.Client.Permission.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建权限失败: %w", err)
	}
	return permission, nil
}

// UpdatePermission is the resolver for the updatePermission field.
func (r *mutationResolver) UpdatePermission(ctx context.Context, id uuid.UUID, input ent.UpdatePermissionInput) (*ent.Permission, error) {
	// 查询权限是否存在
	permission, err := r.Client.Permission.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("权限不存在")
		}
		return nil, fmt.Errorf("查询权限失败: %w", err)
	}

	// 更新权限
	permission, err = permission.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新权限失败: %w", err)
	}
	return permission, nil
}

// DeletePermission is the resolver for the deletePermission field.
func (r *mutationResolver) DeletePermission(ctx context.Context, id uuid.UUID) (*ent.Permission, error) {
	// 查询权限是否存在
	permission, err := r.Client.Permission.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("权限不存在")
		}
		return nil, fmt.Errorf("查询权限失败: %w", err)
	}

	// 删除权限
	err = r.Client.Permission.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除权限失败: %w", err)
	}
	return permission, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	u, err := r.Client.User.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建用户失败: %w", err)
	}
	return u, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input ent.UpdateUserInput) (*ent.User, error) {
	// 查询用户是否存在
	u, err := r.Client.User.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 更新用户
	u, err = u.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新用户失败: %w", err)
	}
	return u, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (*ent.User, error) {
	// 查询用户是否存在
	u, err := r.Client.User.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 删除用户
	err = r.Client.User.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除用户失败: %w", err)
	}
	return u, nil
}

// CreateProcurementPlanType is the resolver for the createProcurementPlanType field.
func (r *mutationResolver) CreateProcurementPlanType(ctx context.Context, input ent.CreateProcurementPlanTypeInput) (*ent.ProcurementPlanType, error) {
	// 创建采购计划类型
	planType, err := r.Client.ProcurementPlanType.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购计划类型失败: %w", err)
	}
	return planType, nil
}

// UpdateProcurementPlanType is the resolver for the updateProcurementPlanType field.
func (r *mutationResolver) UpdateProcurementPlanType(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementPlanTypeInput) (*ent.ProcurementPlanType, error) {
	// 查询采购计划类型是否存在
	planType, err := r.Client.ProcurementPlanType.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划类型不存在")
		}
		return nil, fmt.Errorf("查询采购计划类型失败: %w", err)
	}

	// 更新采购计划类型
	planType, err = planType.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购计划类型失败: %w", err)
	}
	return planType, nil
}

// DeleteProcurementPlanType is the resolver for the deleteProcurementPlanType field.
func (r *mutationResolver) DeleteProcurementPlanType(ctx context.Context, id uuid.UUID) (*ent.ProcurementPlanType, error) {
	// 查询采购计划类型是否存在
	planType, err := r.Client.ProcurementPlanType.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划类型不存在")
		}
		return nil, fmt.Errorf("查询采购计划类型失败: %w", err)
	}

	// 删除采购计划类型
	err = r.Client.ProcurementPlanType.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购计划类型失败: %w", err)
	}
	return planType, nil
}

// CreateProcurementPlan is the resolver for the createProcurementPlan field.
func (r *mutationResolver) CreateProcurementPlan(ctx context.Context, input ent.CreateProcurementPlanInput) (*ent.ProcurementPlan, error) {
	// 校验组织ID是否存在
	if input.OrganizationID == nil {
		return nil, fmt.Errorf("组织ID不能为空")
	}
	_, err := r.Client.Organization.Get(ctx, *input.OrganizationID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("组织不存在")
		}
		return nil, fmt.Errorf("查询组织失败: %w", err)
	}

	// 校验用户ID是否存在
	if input.UserID == nil {
		return nil, fmt.Errorf("用户ID不能为空")
	}
	_, err = r.Client.User.Get(ctx, *input.UserID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("用户不存在")
		}
		return nil, fmt.Errorf("查询用户失败: %w", err)
	}

	// 校验采购计划类型ID是否存在
	if input.ProcurementPlanTypeID == nil {
		return nil, fmt.Errorf("采购计划类型ID不能为空")
	}
	_, err = r.Client.ProcurementPlanType.Get(ctx, *input.ProcurementPlanTypeID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划类型不存在")
		}
		return nil, fmt.Errorf("查询采购计划类型失败: %w", err)
	}

	// 创建采购计划
	plan, err := r.Client.ProcurementPlan.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购计划失败: %w", err)
	}
	return plan, nil
}

// UpdateProcurementPlan is the resolver for the updateProcurementPlan field.
func (r *mutationResolver) UpdateProcurementPlan(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementPlanInput) (*ent.ProcurementPlan, error) {
	// 查询采购计划是否存在
	plan, err := r.Client.ProcurementPlan.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划不存在")
		}
		return nil, fmt.Errorf("查询采购计划失败: %w", err)
	}

	// 校验组织ID是否存在
	if input.OrganizationID != nil {
		_, err = r.Client.Organization.Get(ctx, *input.OrganizationID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("组织不存在")
			}
			return nil, fmt.Errorf("查询组织失败: %w", err)
		}
	}

	// 校验用户ID是否存在
	if input.UserID != nil {
		_, err = r.Client.User.Get(ctx, *input.UserID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("用户不存在")
			}
			return nil, fmt.Errorf("查询用户失败: %w", err)
		}
	}

	// 校验采购计划类型ID是否存在
	if input.ProcurementPlanTypeID != nil {
		_, err = r.Client.ProcurementPlanType.Get(ctx, *input.ProcurementPlanTypeID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("采购计划类型不存在")
			}
			return nil, fmt.Errorf("查询采购计划类型失败: %w", err)
		}
	}

	// 更新采购计划
	plan, err = plan.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购计划失败: %w", err)
	}
	return plan, nil
}

// DeleteProcurementPlan is the resolver for the deleteProcurementPlan field.
func (r *mutationResolver) DeleteProcurementPlan(ctx context.Context, id uuid.UUID) (*ent.ProcurementPlan, error) {
	// 查询采购计划是否存在
	plan, err := r.Client.ProcurementPlan.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划不存在")
		}
		return nil, fmt.Errorf("查询采购计划失败: %w", err)
	}

	// 删除采购计划
	err = r.Client.ProcurementPlan.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购计划失败: %w", err)
	}
	return plan, nil
}

// CreateProcurementReview is the resolver for the createProcurementReview field.
func (r *mutationResolver) CreateProcurementReview(ctx context.Context, input ent.CreateProcurementReviewInput) (*ent.ProcurementReview, error) {
	// 校验采购计划ID是否存在
	if input.ProcurementImplementationID == nil {
		return nil, fmt.Errorf("采购计划ID不能为空")
	}
	_, err := r.Client.ProcurementImplementation.Get(ctx, *input.ProcurementImplementationID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划不存在")
		}
		return nil, fmt.Errorf("查询采购计划失败: %w", err)
	}

	// 创建采购评审
	review, err := r.Client.ProcurementReview.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购评审失败: %w", err)
	}
	return review, nil
}

// UpdateProcurementReview is the resolver for the updateProcurementReview field.
func (r *mutationResolver) UpdateProcurementReview(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementReviewInput) (*ent.ProcurementReview, error) {
	// 查询采购评审是否存在
	review, err := r.Client.ProcurementReview.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购评审不存在")
		}
		return nil, fmt.Errorf("查询采购评审失败: %w", err)
	}

	// 校验采购计划ID是否存在
	if input.ProcurementImplementationID != nil {
		_, err = r.Client.ProcurementImplementation.Get(ctx, *input.ProcurementImplementationID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("采购计划不存在")
			}
			return nil, fmt.Errorf("查询采购计划失败: %w", err)
		}
	}

	// 校验用户ID是否存在
	if input.UserID != nil {
		_, err = r.Client.User.Get(ctx, *input.UserID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("用户不存在")
			}
			return nil, fmt.Errorf("查询用户失败: %w", err)
		}
	}

	// 更新采购评审
	review, err = review.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购评审失败: %w", err)
	}
	return review, nil
}

// DeleteProcurementReview is the resolver for the deleteProcurementReview field.
func (r *mutationResolver) DeleteProcurementReview(ctx context.Context, id uuid.UUID) (*ent.ProcurementReview, error) {
	// 查询采购评审是否存在
	review, err := r.Client.ProcurementReview.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购评审不存在")
		}
		return nil, fmt.Errorf("查询采购评审失败: %w", err)
	}

	// 删除采购评审
	err = r.Client.ProcurementReview.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购评审失败: %w", err)
	}
	return review, nil
}

// CreateProcurementImplementation is the resolver for the createProcurementImplementation field.
func (r *mutationResolver) CreateProcurementImplementation(ctx context.Context, input ent.CreateProcurementImplementationInput) (*ent.ProcurementImplementation, error) {
	// 校验采购计划ID是否存在
	if input.ProcurementPlanID == nil {
		return nil, fmt.Errorf("采购计划ID不能为空")
	}
	_, err := r.Client.ProcurementPlan.Get(ctx, *input.ProcurementPlanID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划不存在")
		}
		return nil, fmt.Errorf("查询采购计划失败: %w", err)
	}

	// 创建采购实施
	implementation, err := r.Client.ProcurementImplementation.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购实施失败: %w", err)
	}
	return implementation, nil
}

// UpdateProcurementImplementation is the resolver for the updateProcurementImplementation field.
func (r *mutationResolver) UpdateProcurementImplementation(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementImplementationInput) (*ent.ProcurementImplementation, error) {
	// 查询采购实施是否存在
	implementation, err := r.Client.ProcurementImplementation.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购实施不存在")
		}
		return nil, fmt.Errorf("查询采购实施失败: %w", err)
	}

	// 校验采购计划ID是否存在
	if input.ProcurementPlanID != nil {
		_, err = r.Client.ProcurementPlan.Get(ctx, *input.ProcurementPlanID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("采购计划不存在")
			}
			return nil, fmt.Errorf("查询采购计划失败: %w", err)
		}
	}

	// 更新采购实施
	implementation, err = implementation.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购实施失败: %w", err)
	}
	return implementation, nil
}

// DeleteProcurementImplementation is the resolver for the deleteProcurementImplementation field.
func (r *mutationResolver) DeleteProcurementImplementation(ctx context.Context, id uuid.UUID) (*ent.ProcurementImplementation, error) {
	// 查询采购实施是否存在
	implementation, err := r.Client.ProcurementImplementation.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购实施不存在")
		}
		return nil, fmt.Errorf("查询采购实施失败: %w", err)
	}

	// 删除采购实施
	err = r.Client.ProcurementImplementation.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购实施失败: %w", err)
	}
	return implementation, nil
}

// CreateProcurementAcceptance is the resolver for the createProcurementAcceptance field.
func (r *mutationResolver) CreateProcurementAcceptance(ctx context.Context, input ent.CreateProcurementAcceptanceInput) (*ent.ProcurementAcceptance, error) {
	// 校验采购计划ID是否存在
	if input.ProcurementImplementationID == nil {
		return nil, fmt.Errorf("采购计划ID不能为空")
	}
	_, err := r.Client.ProcurementImplementation.Get(ctx, *input.ProcurementImplementationID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购计划不存在")
		}
		return nil, fmt.Errorf("查询采购计划失败: %w", err)
	}

	// 创建采购验收
	acceptance, err := r.Client.ProcurementAcceptance.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购验收失败: %w", err)
	}
	return acceptance, nil
}

// UpdateProcurementAcceptance is the resolver for the updateProcurementAcceptance field.
func (r *mutationResolver) UpdateProcurementAcceptance(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementAcceptanceInput) (*ent.ProcurementAcceptance, error) {
	// 查询采购验收是否存在
	acceptance, err := r.Client.ProcurementAcceptance.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购验收不存在")
		}
		return nil, fmt.Errorf("查询采购验收失败: %w", err)
	}

	// 校验采购计划ID是否存在
	if input.ProcurementImplementationID != nil {
		_, err = r.Client.ProcurementImplementation.Get(ctx, *input.ProcurementImplementationID)
		if err != nil {
			if ent.IsNotFound(err) {
				return nil, fmt.Errorf("采购计划不存在")
			}
			return nil, fmt.Errorf("查询采购计划失败: %w", err)
		}
	}

	// 更新采购验收
	acceptance, err = acceptance.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购验收失败: %w", err)
	}
	return acceptance, nil
}

// DeleteProcurementAcceptance is the resolver for the deleteProcurementAcceptance field.
func (r *mutationResolver) DeleteProcurementAcceptance(ctx context.Context, id uuid.UUID) (*ent.ProcurementAcceptance, error) {
	// 查询采购验收是否存在
	acceptance, err := r.Client.ProcurementAcceptance.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购验收不存在")
		}
		return nil, fmt.Errorf("查询采购验收失败: %w", err)
	}

	// 删除采购验收
	err = r.Client.ProcurementAcceptance.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购验收失败: %w", err)
	}
	return acceptance, nil
}

// CreateProcurementExpert is the resolver for the createProcurementExpert field.
func (r *mutationResolver) CreateProcurementExpert(ctx context.Context, input ent.CreateProcurementExpertInput) (*ent.ProcurementExpert, error) {
	// 创建采购专家
	expert, err := r.Client.ProcurementExpert.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建采购专家失败: %w", err)
	}
	return expert, nil
}

// UpdateProcurementExpert is the resolver for the updateProcurementExpert field.
func (r *mutationResolver) UpdateProcurementExpert(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementExpertInput) (*ent.ProcurementExpert, error) {
	// 查询采购专家是否存在
	expert, err := r.Client.ProcurementExpert.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购专家不存在")
		}
		return nil, fmt.Errorf("查询采购专家失败: %w", err)
	}

	// 更新采购专家
	expert, err = expert.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新采购专家失败: %w", err)
	}
	return expert, nil
}

// DeleteProcurementExpert is the resolver for the deleteProcurementExpert field.
func (r *mutationResolver) DeleteProcurementExpert(ctx context.Context, id uuid.UUID) (*ent.ProcurementExpert, error) {
	// 查询采购专家是否存在
	expert, err := r.Client.ProcurementExpert.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("采购专家不存在")
		}
		return nil, fmt.Errorf("查询采购专家失败: %w", err)
	}

	// 删除采购专家
	err = r.Client.ProcurementExpert.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除采购专家失败: %w", err)
	}
	return expert, nil
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input ent.CreateAssetsInput) (*ent.Assets, error) {
	// 创建资产
	asset, err := r.Client.Assets.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建资产失败: %w", err)
	}
	return asset, nil
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, id uuid.UUID, input ent.UpdateAssetsInput) (*ent.Assets, error) {
	// 查询资产是否存在
	asset, err := r.Client.Assets.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产不存在")
		}
		return nil, fmt.Errorf("查询资产失败: %w", err)
	}

	// 更新资产
	asset, err = asset.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新资产失败: %w", err)
	}
	return asset, nil
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id uuid.UUID) (*ent.Assets, error) {
	// 查询资产是否存在
	asset, err := r.Client.Assets.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产不存在")
		}
		return nil, fmt.Errorf("查询资产失败: %w", err)
	}

	// 删除资产
	err = r.Client.Assets.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除资产失败: %w", err)
	}
	return asset, nil
}

// CreateAssetCategory is the resolver for the createAssetCategory field.
func (r *mutationResolver) CreateAssetCategory(ctx context.Context, input ent.CreateAssetCategoryInput) (*ent.AssetCategory, error) {
	// 创建资产分类
	category, err := r.Client.AssetCategory.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建资产分类失败: %w", err)
	}
	return category, nil
}

// UpdateAssetCategory is the resolver for the updateAssetCategory field.
func (r *mutationResolver) UpdateAssetCategory(ctx context.Context, id uuid.UUID, input ent.UpdateAssetCategoryInput) (*ent.AssetCategory, error) {
	// 查询资产分类是否存在
	category, err := r.Client.AssetCategory.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产分类不存在")
		}
		return nil, fmt.Errorf("查询资产分类失败: %w", err)
	}

	// 更新资产分类
	category, err = category.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新资产分类失败: %w", err)
	}
	return category, nil
}

// DeleteAssetCategory is the resolver for the deleteAssetCategory field.
func (r *mutationResolver) DeleteAssetCategory(ctx context.Context, id uuid.UUID) (*ent.AssetCategory, error) {
	// 查询资产分类是否存在
	category, err := r.Client.AssetCategory.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产分类不存在")
		}
		return nil, fmt.Errorf("查询资产分类失败: %w", err)
	}

	// 删除资产分类
	err = r.Client.AssetCategory.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除资产分类失败: %w", err)
	}
	return category, nil
}

// CreateAssetType is the resolver for the createAssetType field.
func (r *mutationResolver) CreateAssetType(ctx context.Context, input ent.CreateAssetTypeInput) (*ent.AssetType, error) {
	// 创建资产类型
	assetType, err := r.Client.AssetType.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("创建资产类型失败: %w", err)
	}
	return assetType, nil
}

// UpdateAssetType is the resolver for the updateAssetType field.
func (r *mutationResolver) UpdateAssetType(ctx context.Context, id uuid.UUID, input ent.UpdateAssetTypeInput) (*ent.AssetType, error) {
	// 查询资产类型是否存在
	assetType, err := r.Client.AssetType.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产类型不存在")
		}
		return nil, fmt.Errorf("查询资产类型失败: %w", err)
	}

	// 更新资产类型
	assetType, err = assetType.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("更新资产类型失败: %w", err)
	}
	return assetType, nil
}

// DeleteAssetType is the resolver for the deleteAssetType field.
func (r *mutationResolver) DeleteAssetType(ctx context.Context, id uuid.UUID) (*ent.AssetType, error) {
	// 查询资产类型是否存在
	assetType, err := r.Client.AssetType.Get(ctx, id)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("资产类型不存在")
		}
		return nil, fmt.Errorf("查询资产类型失败: %w", err)
	}

	// 删除资产类型
	err = r.Client.AssetType.DeleteOneID(id).Exec(ctx)
	if err != nil {
		return nil, fmt.Errorf("删除资产类型失败: %w", err)
	}
	return assetType, nil
}

// CreateLlmModel is the resolver for the createLlmModel field.
func (r *mutationResolver) CreateLlmModel(ctx context.Context, input ent.CreateLlmModelInput) (*ent.LlmModel, error) {
	panic(fmt.Errorf("not implemented: CreateLlmModel - createLlmModel"))
}

// UpdateLlmModel is the resolver for the updateLlmModel field.
func (r *mutationResolver) UpdateLlmModel(ctx context.Context, id uuid.UUID, input ent.UpdateLlmModelInput) (*ent.LlmModel, error) {
	panic(fmt.Errorf("not implemented: UpdateLlmModel - updateLlmModel"))
}

// DeleteLlmModel is the resolver for the deleteLlmModel field.
func (r *mutationResolver) DeleteLlmModel(ctx context.Context, id uuid.UUID) (*ent.LlmModel, error) {
	panic(fmt.Errorf("not implemented: DeleteLlmModel - deleteLlmModel"))
}

// CreateLlmTokenUsage is the resolver for the createLlmTokenUsage field.
func (r *mutationResolver) CreateLlmTokenUsage(ctx context.Context, input ent.CreateLlmTokenUsageInput) (*ent.LlmTokenUsage, error) {
	panic(fmt.Errorf("not implemented: CreateLlmTokenUsage - createLlmTokenUsage"))
}

// UpdateLlmTokenUsage is the resolver for the updateLlmTokenUsage field.
func (r *mutationResolver) UpdateLlmTokenUsage(ctx context.Context, id uuid.UUID, input ent.UpdateLlmTokenUsageInput) (*ent.LlmTokenUsage, error) {
	panic(fmt.Errorf("not implemented: UpdateLlmTokenUsage - updateLlmTokenUsage"))
}

// DeleteLlmTokenUsage is the resolver for the deleteLlmTokenUsage field.
func (r *mutationResolver) DeleteLlmTokenUsage(ctx context.Context, id uuid.UUID) (*ent.LlmTokenUsage, error) {
	panic(fmt.Errorf("not implemented: DeleteLlmTokenUsage - deleteLlmTokenUsage"))
}

// CreateProcurementFraudRisk is the resolver for the createProcurementFraudRisk field.
func (r *mutationResolver) CreateProcurementFraudRisk(ctx context.Context, input ent.CreateProcurementFraudRiskInput) (*ent.ProcurementFraudRisk, error) {
	panic(fmt.Errorf("not implemented: CreateProcurementFraudRisk - createProcurementFraudRisk"))
}

// UpdateProcurementFraudRisk is the resolver for the updateProcurementFraudRisk field.
func (r *mutationResolver) UpdateProcurementFraudRisk(ctx context.Context, id uuid.UUID, input ent.UpdateProcurementFraudRiskInput) (*ent.ProcurementFraudRisk, error) {
	panic(fmt.Errorf("not implemented: UpdateProcurementFraudRisk - updateProcurementFraudRisk"))
}

// DeleteProcurementFraudRisk is the resolver for the deleteProcurementFraudRisk field.
func (r *mutationResolver) DeleteProcurementFraudRisk(ctx context.Context, id uuid.UUID) (*ent.ProcurementFraudRisk, error) {
	panic(fmt.Errorf("not implemented: DeleteProcurementFraudRisk - deleteProcurementFraudRisk"))
}

// CreateLlmProcurementAnalysis is the resolver for the createLlmProcurementAnalysis field.
func (r *mutationResolver) CreateLlmProcurementAnalysis(ctx context.Context, input ent.CreateLlmProcurementAnalysisInput) (*ent.LlmProcurementAnalysis, error) {
	panic(fmt.Errorf("not implemented: CreateLlmProcurementAnalysis - createLlmProcurementAnalysis"))
}

// UpdateLlmProcurementAnalysis is the resolver for the updateLlmProcurementAnalysis field.
func (r *mutationResolver) UpdateLlmProcurementAnalysis(ctx context.Context, id uuid.UUID, input ent.UpdateLlmProcurementAnalysisInput) (*ent.LlmProcurementAnalysis, error) {
	panic(fmt.Errorf("not implemented: UpdateLlmProcurementAnalysis - updateLlmProcurementAnalysis"))
}

// DeleteLlmProcurementAnalysis is the resolver for the deleteLlmProcurementAnalysis field.
func (r *mutationResolver) DeleteLlmProcurementAnalysis(ctx context.Context, id uuid.UUID) (*ent.LlmProcurementAnalysis, error) {
	panic(fmt.Errorf("not implemented: DeleteLlmProcurementAnalysis - deleteLlmProcurementAnalysis"))
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id uuid.UUID) (*ent.User, error) {
	claims, err := auth.GetUserClaimsFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	// 检查是否是本人
	if claims.UserID != id {
		return nil, fmt.Errorf("无权查看他人资料")
	}
	return r.Client.User.Query().Where(user.ID(id)).Only(ctx)
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.OrganizationWhereInput) ([]*ent.OrganizationConnection, error) {
	// 查询组织列表
	query := r.Client.Organization.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询组织列表失败: %w", err)
	}

	return []*ent.OrganizationConnection{conn}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.UserWhereInput) ([]*ent.UserConnection, error) {
	// 查询用户列表
	query := r.Client.User.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询用户列表失败: %w", err)
	}

	return []*ent.UserConnection{conn}, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.RoleWhereInput) ([]*ent.RoleConnection, error) {
	// 查询角色列表
	query := r.Client.Role.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询角色列表失败: %w", err)
	}

	return []*ent.RoleConnection{conn}, nil
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.PermissionWhereInput) ([]*ent.PermissionConnection, error) {
	// 查询权限列表
	query := r.Client.Permission.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询权限列表失败: %w", err)
	}

	return []*ent.PermissionConnection{conn}, nil
}

// ProcurementPlanTypes is the resolver for the procurementPlanTypes field.
func (r *queryResolver) ProcurementPlanTypes(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementPlanTypeWhereInput) ([]*ent.ProcurementPlanTypeConnection, error) {
	// 查询采购计划类型列表
	query := r.Client.ProcurementPlanType.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购计划类型列表失败: %w", err)
	}

	return []*ent.ProcurementPlanTypeConnection{conn}, nil
}

// ProcurementPlans is the resolver for the procurementPlans field.
func (r *queryResolver) ProcurementPlans(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementPlanWhereInput) ([]*ent.ProcurementPlanConnection, error) {
	// 查询采购计划列表
	query := r.Client.ProcurementPlan.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购计划列表失败: %w", err)
	}

	return []*ent.ProcurementPlanConnection{conn}, nil
}

// ProcurementImplementations is the resolver for the procurementImplementations field.
func (r *queryResolver) ProcurementImplementations(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementImplementationWhereInput) ([]*ent.ProcurementImplementationConnection, error) {
	// 查询采购实施列表
	query := r.Client.ProcurementImplementation.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购实施列表失败: %w", err)
	}

	return []*ent.ProcurementImplementationConnection{conn}, nil
}

// ProcurementExperts is the resolver for the procurementExperts field.
func (r *queryResolver) ProcurementExperts(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementExpertWhereInput) ([]*ent.ProcurementExpertConnection, error) {
	// 查询采购专家列表
	query := r.Client.ProcurementExpert.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购专家列表失败: %w", err)
	}

	return []*ent.ProcurementExpertConnection{conn}, nil
}

// ProcurementAcceptances is the resolver for the procurementAcceptances field.
func (r *queryResolver) ProcurementAcceptances(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementAcceptanceWhereInput) ([]*ent.ProcurementAcceptanceConnection, error) {
	// 查询采购验收列表
	query := r.Client.ProcurementAcceptance.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购验收列表失败: %w", err)
	}

	return []*ent.ProcurementAcceptanceConnection{conn}, nil
}

// ProcurementReviews is the resolver for the procurementReviews field.
func (r *queryResolver) ProcurementReviews(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementReviewWhereInput) ([]*ent.ProcurementReviewConnection, error) {
	// 查询采购评审列表
	query := r.Client.ProcurementReview.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询采购评审列表失败: %w", err)
	}

	return []*ent.ProcurementReviewConnection{conn}, nil
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.AssetsWhereInput) ([]*ent.AssetsConnection, error) {
	// 查询资产列表
	query := r.Client.Assets.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询资产列表失败: %w", err)
	}

	return []*ent.AssetsConnection{conn}, nil
}

// AssetCategories is the resolver for the assetCategories field.
func (r *queryResolver) AssetCategories(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.AssetCategoryWhereInput) ([]*ent.AssetCategoryConnection, error) {
	// 查询资产分类列表
	query := r.Client.AssetCategory.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询资产分类列表失败: %w", err)
	}

	return []*ent.AssetCategoryConnection{conn}, nil
}

// AssetTypes is the resolver for the assetTypes field.
func (r *queryResolver) AssetTypes(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.AssetTypeWhereInput) ([]*ent.AssetTypeConnection, error) {
	// 查询资产类型列表
	query := r.Client.AssetType.Query()
	if where != nil {
		where.Filter(query)
	}

	// 应用分页
	conn, err := query.Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, fmt.Errorf("查询资产类型列表失败: %w", err)
	}

	return []*ent.AssetTypeConnection{conn}, nil
}

// LlmModels is the resolver for the llmModels field.
func (r *queryResolver) LlmModels(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.LlmModelWhereInput) ([]*ent.LlmModelConnection, error) {
	panic(fmt.Errorf("not implemented: LlmModels - llmModels"))
}

// LlmTokenUsages is the resolver for the llmTokenUsages field.
func (r *queryResolver) LlmTokenUsages(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.LlmTokenUsageWhereInput) ([]*ent.LlmTokenUsageConnection, error) {
	panic(fmt.Errorf("not implemented: LlmTokenUsages - llmTokenUsages"))
}

// ProcurementFraudRisks is the resolver for the procurementFraudRisks field.
func (r *queryResolver) ProcurementFraudRisks(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.ProcurementFraudRiskWhereInput) ([]*ent.ProcurementFraudRiskConnection, error) {
	panic(fmt.Errorf("not implemented: ProcurementFraudRisks - procurementFraudRisks"))
}

// LlmProcurementAnalyses is the resolver for the llmProcurementAnalyses field.
func (r *queryResolver) LlmProcurementAnalyses(ctx context.Context, after *entgql.Cursor[uuid.UUID], before *entgql.Cursor[uuid.UUID], first *int, last *int, where *ent.LlmProcurementAnalysisWhereInput) ([]*ent.LlmProcurementAnalysisConnection, error) {
	panic(fmt.Errorf("not implemented: LlmProcurementAnalyses - llmProcurementAnalyses"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
