// Code generated by ent, DO NOT EDIT.

package llmmodel

import (
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldID, id))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldModelName, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldProvider, v))
}

// ModelCode applies equality check predicate on the "model_code" field. It's identical to ModelCodeEQ.
func ModelCode(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldModelCode, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldAPIKey, v))
}

// APIEndpoint applies equality check predicate on the "api_endpoint" field. It's identical to APIEndpointEQ.
func APIEndpoint(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldAPIEndpoint, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldEnabled, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldMaxTokens, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContainsFold(FieldModelName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContainsFold(FieldProvider, v))
}

// ModelCodeEQ applies the EQ predicate on the "model_code" field.
func ModelCodeEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldModelCode, v))
}

// ModelCodeNEQ applies the NEQ predicate on the "model_code" field.
func ModelCodeNEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldModelCode, v))
}

// ModelCodeIn applies the In predicate on the "model_code" field.
func ModelCodeIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldModelCode, vs...))
}

// ModelCodeNotIn applies the NotIn predicate on the "model_code" field.
func ModelCodeNotIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldModelCode, vs...))
}

// ModelCodeGT applies the GT predicate on the "model_code" field.
func ModelCodeGT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldModelCode, v))
}

// ModelCodeGTE applies the GTE predicate on the "model_code" field.
func ModelCodeGTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldModelCode, v))
}

// ModelCodeLT applies the LT predicate on the "model_code" field.
func ModelCodeLT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldModelCode, v))
}

// ModelCodeLTE applies the LTE predicate on the "model_code" field.
func ModelCodeLTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldModelCode, v))
}

// ModelCodeContains applies the Contains predicate on the "model_code" field.
func ModelCodeContains(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContains(FieldModelCode, v))
}

// ModelCodeHasPrefix applies the HasPrefix predicate on the "model_code" field.
func ModelCodeHasPrefix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasPrefix(FieldModelCode, v))
}

// ModelCodeHasSuffix applies the HasSuffix predicate on the "model_code" field.
func ModelCodeHasSuffix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasSuffix(FieldModelCode, v))
}

// ModelCodeEqualFold applies the EqualFold predicate on the "model_code" field.
func ModelCodeEqualFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEqualFold(FieldModelCode, v))
}

// ModelCodeContainsFold applies the ContainsFold predicate on the "model_code" field.
func ModelCodeContainsFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContainsFold(FieldModelCode, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContainsFold(FieldAPIKey, v))
}

// APIEndpointEQ applies the EQ predicate on the "api_endpoint" field.
func APIEndpointEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldAPIEndpoint, v))
}

// APIEndpointNEQ applies the NEQ predicate on the "api_endpoint" field.
func APIEndpointNEQ(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldAPIEndpoint, v))
}

// APIEndpointIn applies the In predicate on the "api_endpoint" field.
func APIEndpointIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldAPIEndpoint, vs...))
}

// APIEndpointNotIn applies the NotIn predicate on the "api_endpoint" field.
func APIEndpointNotIn(vs ...string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldAPIEndpoint, vs...))
}

// APIEndpointGT applies the GT predicate on the "api_endpoint" field.
func APIEndpointGT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldAPIEndpoint, v))
}

// APIEndpointGTE applies the GTE predicate on the "api_endpoint" field.
func APIEndpointGTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldAPIEndpoint, v))
}

// APIEndpointLT applies the LT predicate on the "api_endpoint" field.
func APIEndpointLT(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldAPIEndpoint, v))
}

// APIEndpointLTE applies the LTE predicate on the "api_endpoint" field.
func APIEndpointLTE(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldAPIEndpoint, v))
}

// APIEndpointContains applies the Contains predicate on the "api_endpoint" field.
func APIEndpointContains(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContains(FieldAPIEndpoint, v))
}

// APIEndpointHasPrefix applies the HasPrefix predicate on the "api_endpoint" field.
func APIEndpointHasPrefix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasPrefix(FieldAPIEndpoint, v))
}

// APIEndpointHasSuffix applies the HasSuffix predicate on the "api_endpoint" field.
func APIEndpointHasSuffix(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldHasSuffix(FieldAPIEndpoint, v))
}

// APIEndpointIsNil applies the IsNil predicate on the "api_endpoint" field.
func APIEndpointIsNil() predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIsNull(FieldAPIEndpoint))
}

// APIEndpointNotNil applies the NotNil predicate on the "api_endpoint" field.
func APIEndpointNotNil() predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotNull(FieldAPIEndpoint))
}

// APIEndpointEqualFold applies the EqualFold predicate on the "api_endpoint" field.
func APIEndpointEqualFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEqualFold(FieldAPIEndpoint, v))
}

// APIEndpointContainsFold applies the ContainsFold predicate on the "api_endpoint" field.
func APIEndpointContainsFold(v string) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldContainsFold(FieldAPIEndpoint, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldEnabled, v))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldMaxTokens, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LlmModel {
	return predicate.LlmModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.LlmModel {
	return predicate.LlmModel(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.LlmModel {
	return predicate.LlmModel(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LlmModel) predicate.LlmModel {
	return predicate.LlmModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LlmModel) predicate.LlmModel {
	return predicate.LlmModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LlmModel) predicate.LlmModel {
	return predicate.LlmModel(sql.NotPredicates(p))
}
