// Code generated by ent, DO NOT EDIT.

package llmprocurementanalysis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the llmprocurementanalysis type in the database.
	Label = "llm_procurement_analysis"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "log_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldProcurementPlanID holds the string denoting the procurement_plan_id field in the database.
	FieldProcurementPlanID = "procurement_plan_id"
	// FieldProcurementImplementationID holds the string denoting the procurement_implementation_id field in the database.
	FieldProcurementImplementationID = "procurement_implementation_id"
	// FieldAnalysisResult holds the string denoting the analysis_result field in the database.
	FieldAnalysisResult = "analysis_result"
	// FieldTokenUsageID holds the string denoting the token_usage_id field in the database.
	FieldTokenUsageID = "token_usage_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the llmprocurementanalysis in the database.
	Table = "llm_procurement_analysis"
)

// Columns holds all SQL columns for llmprocurementanalysis fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldProcurementPlanID,
	FieldProcurementImplementationID,
	FieldAnalysisResult,
	FieldTokenUsageID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LlmProcurementAnalysis queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByProcurementPlanID orders the results by the procurement_plan_id field.
func ByProcurementPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcurementPlanID, opts...).ToFunc()
}

// ByProcurementImplementationID orders the results by the procurement_implementation_id field.
func ByProcurementImplementationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcurementImplementationID, opts...).ToFunc()
}

// ByAnalysisResult orders the results by the analysis_result field.
func ByAnalysisResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalysisResult, opts...).ToFunc()
}

// ByTokenUsageID orders the results by the token_usage_id field.
func ByTokenUsageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenUsageID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
