// Code generated by ent, DO NOT EDIT.

package permission

import (
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldID, id))
}

// PermissionName applies equality check predicate on the "permission_name" field. It's identical to PermissionNameEQ.
func PermissionName(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionName, v))
}

// PermissionCode applies equality check predicate on the "permission_code" field. It's identical to PermissionCodeEQ.
func PermissionCode(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionCode, v))
}

// PermissionDescription applies equality check predicate on the "permission_description" field. It's identical to PermissionDescriptionEQ.
func PermissionDescription(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionDescription, v))
}

// PermissionFlag applies equality check predicate on the "permission_flag" field. It's identical to PermissionFlagEQ.
func PermissionFlag(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionFlag, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldUpdatedAt, v))
}

// PermissionNameEQ applies the EQ predicate on the "permission_name" field.
func PermissionNameEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionName, v))
}

// PermissionNameNEQ applies the NEQ predicate on the "permission_name" field.
func PermissionNameNEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldPermissionName, v))
}

// PermissionNameIn applies the In predicate on the "permission_name" field.
func PermissionNameIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldPermissionName, vs...))
}

// PermissionNameNotIn applies the NotIn predicate on the "permission_name" field.
func PermissionNameNotIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldPermissionName, vs...))
}

// PermissionNameGT applies the GT predicate on the "permission_name" field.
func PermissionNameGT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldPermissionName, v))
}

// PermissionNameGTE applies the GTE predicate on the "permission_name" field.
func PermissionNameGTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldPermissionName, v))
}

// PermissionNameLT applies the LT predicate on the "permission_name" field.
func PermissionNameLT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldPermissionName, v))
}

// PermissionNameLTE applies the LTE predicate on the "permission_name" field.
func PermissionNameLTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldPermissionName, v))
}

// PermissionNameContains applies the Contains predicate on the "permission_name" field.
func PermissionNameContains(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContains(FieldPermissionName, v))
}

// PermissionNameHasPrefix applies the HasPrefix predicate on the "permission_name" field.
func PermissionNameHasPrefix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasPrefix(FieldPermissionName, v))
}

// PermissionNameHasSuffix applies the HasSuffix predicate on the "permission_name" field.
func PermissionNameHasSuffix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasSuffix(FieldPermissionName, v))
}

// PermissionNameEqualFold applies the EqualFold predicate on the "permission_name" field.
func PermissionNameEqualFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEqualFold(FieldPermissionName, v))
}

// PermissionNameContainsFold applies the ContainsFold predicate on the "permission_name" field.
func PermissionNameContainsFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContainsFold(FieldPermissionName, v))
}

// PermissionCodeEQ applies the EQ predicate on the "permission_code" field.
func PermissionCodeEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionCode, v))
}

// PermissionCodeNEQ applies the NEQ predicate on the "permission_code" field.
func PermissionCodeNEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldPermissionCode, v))
}

// PermissionCodeIn applies the In predicate on the "permission_code" field.
func PermissionCodeIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldPermissionCode, vs...))
}

// PermissionCodeNotIn applies the NotIn predicate on the "permission_code" field.
func PermissionCodeNotIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldPermissionCode, vs...))
}

// PermissionCodeGT applies the GT predicate on the "permission_code" field.
func PermissionCodeGT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldPermissionCode, v))
}

// PermissionCodeGTE applies the GTE predicate on the "permission_code" field.
func PermissionCodeGTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldPermissionCode, v))
}

// PermissionCodeLT applies the LT predicate on the "permission_code" field.
func PermissionCodeLT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldPermissionCode, v))
}

// PermissionCodeLTE applies the LTE predicate on the "permission_code" field.
func PermissionCodeLTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldPermissionCode, v))
}

// PermissionCodeContains applies the Contains predicate on the "permission_code" field.
func PermissionCodeContains(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContains(FieldPermissionCode, v))
}

// PermissionCodeHasPrefix applies the HasPrefix predicate on the "permission_code" field.
func PermissionCodeHasPrefix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasPrefix(FieldPermissionCode, v))
}

// PermissionCodeHasSuffix applies the HasSuffix predicate on the "permission_code" field.
func PermissionCodeHasSuffix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasSuffix(FieldPermissionCode, v))
}

// PermissionCodeEqualFold applies the EqualFold predicate on the "permission_code" field.
func PermissionCodeEqualFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEqualFold(FieldPermissionCode, v))
}

// PermissionCodeContainsFold applies the ContainsFold predicate on the "permission_code" field.
func PermissionCodeContainsFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContainsFold(FieldPermissionCode, v))
}

// PermissionDescriptionEQ applies the EQ predicate on the "permission_description" field.
func PermissionDescriptionEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionDescription, v))
}

// PermissionDescriptionNEQ applies the NEQ predicate on the "permission_description" field.
func PermissionDescriptionNEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldPermissionDescription, v))
}

// PermissionDescriptionIn applies the In predicate on the "permission_description" field.
func PermissionDescriptionIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldPermissionDescription, vs...))
}

// PermissionDescriptionNotIn applies the NotIn predicate on the "permission_description" field.
func PermissionDescriptionNotIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldPermissionDescription, vs...))
}

// PermissionDescriptionGT applies the GT predicate on the "permission_description" field.
func PermissionDescriptionGT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldPermissionDescription, v))
}

// PermissionDescriptionGTE applies the GTE predicate on the "permission_description" field.
func PermissionDescriptionGTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldPermissionDescription, v))
}

// PermissionDescriptionLT applies the LT predicate on the "permission_description" field.
func PermissionDescriptionLT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldPermissionDescription, v))
}

// PermissionDescriptionLTE applies the LTE predicate on the "permission_description" field.
func PermissionDescriptionLTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldPermissionDescription, v))
}

// PermissionDescriptionContains applies the Contains predicate on the "permission_description" field.
func PermissionDescriptionContains(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContains(FieldPermissionDescription, v))
}

// PermissionDescriptionHasPrefix applies the HasPrefix predicate on the "permission_description" field.
func PermissionDescriptionHasPrefix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasPrefix(FieldPermissionDescription, v))
}

// PermissionDescriptionHasSuffix applies the HasSuffix predicate on the "permission_description" field.
func PermissionDescriptionHasSuffix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasSuffix(FieldPermissionDescription, v))
}

// PermissionDescriptionEqualFold applies the EqualFold predicate on the "permission_description" field.
func PermissionDescriptionEqualFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEqualFold(FieldPermissionDescription, v))
}

// PermissionDescriptionContainsFold applies the ContainsFold predicate on the "permission_description" field.
func PermissionDescriptionContainsFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContainsFold(FieldPermissionDescription, v))
}

// PermissionFlagEQ applies the EQ predicate on the "permission_flag" field.
func PermissionFlagEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldPermissionFlag, v))
}

// PermissionFlagNEQ applies the NEQ predicate on the "permission_flag" field.
func PermissionFlagNEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldPermissionFlag, v))
}

// PermissionFlagIn applies the In predicate on the "permission_flag" field.
func PermissionFlagIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldPermissionFlag, vs...))
}

// PermissionFlagNotIn applies the NotIn predicate on the "permission_flag" field.
func PermissionFlagNotIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldPermissionFlag, vs...))
}

// PermissionFlagGT applies the GT predicate on the "permission_flag" field.
func PermissionFlagGT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldPermissionFlag, v))
}

// PermissionFlagGTE applies the GTE predicate on the "permission_flag" field.
func PermissionFlagGTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldPermissionFlag, v))
}

// PermissionFlagLT applies the LT predicate on the "permission_flag" field.
func PermissionFlagLT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldPermissionFlag, v))
}

// PermissionFlagLTE applies the LTE predicate on the "permission_flag" field.
func PermissionFlagLTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldPermissionFlag, v))
}

// PermissionFlagContains applies the Contains predicate on the "permission_flag" field.
func PermissionFlagContains(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContains(FieldPermissionFlag, v))
}

// PermissionFlagHasPrefix applies the HasPrefix predicate on the "permission_flag" field.
func PermissionFlagHasPrefix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasPrefix(FieldPermissionFlag, v))
}

// PermissionFlagHasSuffix applies the HasSuffix predicate on the "permission_flag" field.
func PermissionFlagHasSuffix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasSuffix(FieldPermissionFlag, v))
}

// PermissionFlagEqualFold applies the EqualFold predicate on the "permission_flag" field.
func PermissionFlagEqualFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEqualFold(FieldPermissionFlag, v))
}

// PermissionFlagContainsFold applies the ContainsFold predicate on the "permission_flag" field.
func PermissionFlagContainsFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContainsFold(FieldPermissionFlag, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Permission {
	return predicate.Permission(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Permission {
	return predicate.Permission(sql.FieldNotNull(FieldUpdatedAt))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.Permission {
	return predicate.Permission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, RoleTable, RolePrimaryKey...),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Role
		step.Edge.Schema = schemaConfig.RolePermission
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.Permission {
	return predicate.Permission(func(s *sql.Selector) {
		step := newRoleStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Role
		step.Edge.Schema = schemaConfig.RolePermission
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.NotPredicates(p))
}
