// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"moon/ent/assetcategory"
	"moon/ent/assets"
	"moon/ent/assettype"
	"moon/ent/organization"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Assets is the model entity for the Assets schema.
type Assets struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AssetName holds the value of the "asset_name" field.
	AssetName string `json:"asset_name,omitempty"`
	// AssetCode holds the value of the "asset_code" field.
	AssetCode string `json:"asset_code,omitempty"`
	// AssetDescription holds the value of the "asset_description" field.
	AssetDescription string `json:"asset_description,omitempty"`
	// AssetFlag holds the value of the "asset_flag" field.
	AssetFlag string `json:"asset_flag,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// PurchasePrice holds the value of the "purchase_price" field.
	PurchasePrice float64 `json:"purchase_price,omitempty"`
	// DepreciationPrice holds the value of the "depreciation_price" field.
	DepreciationPrice float64 `json:"depreciation_price,omitempty"`
	// PurchaseDate holds the value of the "purchase_date" field.
	PurchaseDate *time.Time `json:"purchase_date,omitempty"`
	// Manufacturer holds the value of the "manufacturer" field.
	Manufacturer string `json:"manufacturer,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// OtherMetadata holds the value of the "other_metadata" field.
	OtherMetadata map[string]interface{} `json:"other_metadata,omitempty"`
	// AssetTypeID holds the value of the "asset_type_id" field.
	AssetTypeID *uuid.UUID `json:"asset_type_id,omitempty"`
	// AssetCategoryID holds the value of the "asset_category_id" field.
	AssetCategoryID *uuid.UUID `json:"asset_category_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *uuid.UUID `json:"organization_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssetsQuery when eager-loading is set.
	Edges        AssetsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AssetsEdges holds the relations/edges for other nodes in the graph.
type AssetsEdges struct {
	// AssetCategory holds the value of the asset_category edge.
	AssetCategory *AssetCategory `json:"asset_category,omitempty"`
	// AssetType holds the value of the asset_type edge.
	AssetType *AssetType `json:"asset_type,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// AssetCategoryOrErr returns the AssetCategory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetsEdges) AssetCategoryOrErr() (*AssetCategory, error) {
	if e.AssetCategory != nil {
		return e.AssetCategory, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: assetcategory.Label}
	}
	return nil, &NotLoadedError{edge: "asset_category"}
}

// AssetTypeOrErr returns the AssetType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetsEdges) AssetTypeOrErr() (*AssetType, error) {
	if e.AssetType != nil {
		return e.AssetType, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: assettype.Label}
	}
	return nil, &NotLoadedError{edge: "asset_type"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssetsEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Assets) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assets.FieldAssetTypeID, assets.FieldAssetCategoryID, assets.FieldOrganizationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case assets.FieldOtherMetadata:
			values[i] = new([]byte)
		case assets.FieldPurchasePrice, assets.FieldDepreciationPrice:
			values[i] = new(sql.NullFloat64)
		case assets.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case assets.FieldAssetName, assets.FieldAssetCode, assets.FieldAssetDescription, assets.FieldAssetFlag, assets.FieldLocation, assets.FieldManufacturer, assets.FieldModel:
			values[i] = new(sql.NullString)
		case assets.FieldPurchaseDate, assets.FieldCreatedAt, assets.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case assets.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Assets fields.
func (_m *Assets) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assets.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case assets.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				_m.AssetName = value.String
			}
		case assets.FieldAssetCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_code", values[i])
			} else if value.Valid {
				_m.AssetCode = value.String
			}
		case assets.FieldAssetDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_description", values[i])
			} else if value.Valid {
				_m.AssetDescription = value.String
			}
		case assets.FieldAssetFlag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_flag", values[i])
			} else if value.Valid {
				_m.AssetFlag = value.String
			}
		case assets.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case assets.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case assets.FieldPurchasePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_price", values[i])
			} else if value.Valid {
				_m.PurchasePrice = value.Float64
			}
		case assets.FieldDepreciationPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field depreciation_price", values[i])
			} else if value.Valid {
				_m.DepreciationPrice = value.Float64
			}
		case assets.FieldPurchaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_date", values[i])
			} else if value.Valid {
				_m.PurchaseDate = new(time.Time)
				*_m.PurchaseDate = value.Time
			}
		case assets.FieldManufacturer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manufacturer", values[i])
			} else if value.Valid {
				_m.Manufacturer = value.String
			}
		case assets.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case assets.FieldOtherMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field other_metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OtherMetadata); err != nil {
					return fmt.Errorf("unmarshal field other_metadata: %w", err)
				}
			}
		case assets.FieldAssetTypeID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field asset_type_id", values[i])
			} else if value.Valid {
				_m.AssetTypeID = new(uuid.UUID)
				*_m.AssetTypeID = *value.S.(*uuid.UUID)
			}
		case assets.FieldAssetCategoryID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field asset_category_id", values[i])
			} else if value.Valid {
				_m.AssetCategoryID = new(uuid.UUID)
				*_m.AssetCategoryID = *value.S.(*uuid.UUID)
			}
		case assets.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(uuid.UUID)
				*_m.OrganizationID = *value.S.(*uuid.UUID)
			}
		case assets.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case assets.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Assets.
// This includes values selected through modifiers, order, etc.
func (_m *Assets) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAssetCategory queries the "asset_category" edge of the Assets entity.
func (_m *Assets) QueryAssetCategory() *AssetCategoryQuery {
	return NewAssetsClient(_m.config).QueryAssetCategory(_m)
}

// QueryAssetType queries the "asset_type" edge of the Assets entity.
func (_m *Assets) QueryAssetType() *AssetTypeQuery {
	return NewAssetsClient(_m.config).QueryAssetType(_m)
}

// QueryOrganization queries the "organization" edge of the Assets entity.
func (_m *Assets) QueryOrganization() *OrganizationQuery {
	return NewAssetsClient(_m.config).QueryOrganization(_m)
}

// Update returns a builder for updating this Assets.
// Note that you need to call Assets.Unwrap() before calling this method if this Assets
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Assets) Update() *AssetsUpdateOne {
	return NewAssetsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Assets entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Assets) Unwrap() *Assets {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Assets is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Assets) String() string {
	var builder strings.Builder
	builder.WriteString("Assets(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("asset_name=")
	builder.WriteString(_m.AssetName)
	builder.WriteString(", ")
	builder.WriteString("asset_code=")
	builder.WriteString(_m.AssetCode)
	builder.WriteString(", ")
	builder.WriteString("asset_description=")
	builder.WriteString(_m.AssetDescription)
	builder.WriteString(", ")
	builder.WriteString("asset_flag=")
	builder.WriteString(_m.AssetFlag)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("purchase_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.PurchasePrice))
	builder.WriteString(", ")
	builder.WriteString("depreciation_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepreciationPrice))
	builder.WriteString(", ")
	if v := _m.PurchaseDate; v != nil {
		builder.WriteString("purchase_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("manufacturer=")
	builder.WriteString(_m.Manufacturer)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("other_metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.OtherMetadata))
	builder.WriteString(", ")
	if v := _m.AssetTypeID; v != nil {
		builder.WriteString("asset_type_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssetCategoryID; v != nil {
		builder.WriteString("asset_category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AssetsSlice is a parsable slice of Assets.
type AssetsSlice []*Assets
