// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moon/ent/assetcategory"
	"moon/ent/assets"
	"moon/ent/assettype"
	"moon/ent/organization"
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// AssetsUpdate is the builder for updating Assets entities.
type AssetsUpdate struct {
	config
	hooks    []Hook
	mutation *AssetsMutation
}

// Where appends a list predicates to the AssetsUpdate builder.
func (_u *AssetsUpdate) Where(ps ...predicate.Assets) *AssetsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAssetName sets the "asset_name" field.
func (_u *AssetsUpdate) SetAssetName(v string) *AssetsUpdate {
	_u.mutation.SetAssetName(v)
	return _u
}

// SetNillableAssetName sets the "asset_name" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetName(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetAssetName(*v)
	}
	return _u
}

// SetAssetCode sets the "asset_code" field.
func (_u *AssetsUpdate) SetAssetCode(v string) *AssetsUpdate {
	_u.mutation.SetAssetCode(v)
	return _u
}

// SetNillableAssetCode sets the "asset_code" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetCode(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetAssetCode(*v)
	}
	return _u
}

// SetAssetDescription sets the "asset_description" field.
func (_u *AssetsUpdate) SetAssetDescription(v string) *AssetsUpdate {
	_u.mutation.SetAssetDescription(v)
	return _u
}

// SetNillableAssetDescription sets the "asset_description" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetDescription(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetAssetDescription(*v)
	}
	return _u
}

// SetAssetFlag sets the "asset_flag" field.
func (_u *AssetsUpdate) SetAssetFlag(v string) *AssetsUpdate {
	_u.mutation.SetAssetFlag(v)
	return _u
}

// SetNillableAssetFlag sets the "asset_flag" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetFlag(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetAssetFlag(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *AssetsUpdate) SetQuantity(v int) *AssetsUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableQuantity(v *int) *AssetsUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *AssetsUpdate) AddQuantity(v int) *AssetsUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetLocation sets the "location" field.
func (_u *AssetsUpdate) SetLocation(v string) *AssetsUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableLocation(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetPurchasePrice sets the "purchase_price" field.
func (_u *AssetsUpdate) SetPurchasePrice(v float64) *AssetsUpdate {
	_u.mutation.ResetPurchasePrice()
	_u.mutation.SetPurchasePrice(v)
	return _u
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillablePurchasePrice(v *float64) *AssetsUpdate {
	if v != nil {
		_u.SetPurchasePrice(*v)
	}
	return _u
}

// AddPurchasePrice adds value to the "purchase_price" field.
func (_u *AssetsUpdate) AddPurchasePrice(v float64) *AssetsUpdate {
	_u.mutation.AddPurchasePrice(v)
	return _u
}

// SetDepreciationPrice sets the "depreciation_price" field.
func (_u *AssetsUpdate) SetDepreciationPrice(v float64) *AssetsUpdate {
	_u.mutation.ResetDepreciationPrice()
	_u.mutation.SetDepreciationPrice(v)
	return _u
}

// SetNillableDepreciationPrice sets the "depreciation_price" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableDepreciationPrice(v *float64) *AssetsUpdate {
	if v != nil {
		_u.SetDepreciationPrice(*v)
	}
	return _u
}

// AddDepreciationPrice adds value to the "depreciation_price" field.
func (_u *AssetsUpdate) AddDepreciationPrice(v float64) *AssetsUpdate {
	_u.mutation.AddDepreciationPrice(v)
	return _u
}

// SetPurchaseDate sets the "purchase_date" field.
func (_u *AssetsUpdate) SetPurchaseDate(v time.Time) *AssetsUpdate {
	_u.mutation.SetPurchaseDate(v)
	return _u
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillablePurchaseDate(v *time.Time) *AssetsUpdate {
	if v != nil {
		_u.SetPurchaseDate(*v)
	}
	return _u
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (_u *AssetsUpdate) ClearPurchaseDate() *AssetsUpdate {
	_u.mutation.ClearPurchaseDate()
	return _u
}

// SetManufacturer sets the "manufacturer" field.
func (_u *AssetsUpdate) SetManufacturer(v string) *AssetsUpdate {
	_u.mutation.SetManufacturer(v)
	return _u
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableManufacturer(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetManufacturer(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AssetsUpdate) SetModel(v string) *AssetsUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableModel(v *string) *AssetsUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOtherMetadata sets the "other_metadata" field.
func (_u *AssetsUpdate) SetOtherMetadata(v map[string]interface{}) *AssetsUpdate {
	_u.mutation.SetOtherMetadata(v)
	return _u
}

// ClearOtherMetadata clears the value of the "other_metadata" field.
func (_u *AssetsUpdate) ClearOtherMetadata() *AssetsUpdate {
	_u.mutation.ClearOtherMetadata()
	return _u
}

// SetAssetTypeID sets the "asset_type_id" field.
func (_u *AssetsUpdate) SetAssetTypeID(v uuid.UUID) *AssetsUpdate {
	_u.mutation.SetAssetTypeID(v)
	return _u
}

// SetNillableAssetTypeID sets the "asset_type_id" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetTypeID(v *uuid.UUID) *AssetsUpdate {
	if v != nil {
		_u.SetAssetTypeID(*v)
	}
	return _u
}

// ClearAssetTypeID clears the value of the "asset_type_id" field.
func (_u *AssetsUpdate) ClearAssetTypeID() *AssetsUpdate {
	_u.mutation.ClearAssetTypeID()
	return _u
}

// SetAssetCategoryID sets the "asset_category_id" field.
func (_u *AssetsUpdate) SetAssetCategoryID(v uuid.UUID) *AssetsUpdate {
	_u.mutation.SetAssetCategoryID(v)
	return _u
}

// SetNillableAssetCategoryID sets the "asset_category_id" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableAssetCategoryID(v *uuid.UUID) *AssetsUpdate {
	if v != nil {
		_u.SetAssetCategoryID(*v)
	}
	return _u
}

// ClearAssetCategoryID clears the value of the "asset_category_id" field.
func (_u *AssetsUpdate) ClearAssetCategoryID() *AssetsUpdate {
	_u.mutation.ClearAssetCategoryID()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *AssetsUpdate) SetOrganizationID(v uuid.UUID) *AssetsUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableOrganizationID(v *uuid.UUID) *AssetsUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *AssetsUpdate) ClearOrganizationID() *AssetsUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetsUpdate) SetCreatedAt(v time.Time) *AssetsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableCreatedAt(v *time.Time) *AssetsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetsUpdate) SetUpdatedAt(v time.Time) *AssetsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AssetsUpdate) SetNillableUpdatedAt(v *time.Time) *AssetsUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AssetsUpdate) ClearUpdatedAt() *AssetsUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetAssetCategory sets the "asset_category" edge to the AssetCategory entity.
func (_u *AssetsUpdate) SetAssetCategory(v *AssetCategory) *AssetsUpdate {
	return _u.SetAssetCategoryID(v.ID)
}

// SetAssetType sets the "asset_type" edge to the AssetType entity.
func (_u *AssetsUpdate) SetAssetType(v *AssetType) *AssetsUpdate {
	return _u.SetAssetTypeID(v.ID)
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *AssetsUpdate) SetOrganization(v *Organization) *AssetsUpdate {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the AssetsMutation object of the builder.
func (_u *AssetsUpdate) Mutation() *AssetsMutation {
	return _u.mutation
}

// ClearAssetCategory clears the "asset_category" edge to the AssetCategory entity.
func (_u *AssetsUpdate) ClearAssetCategory() *AssetsUpdate {
	_u.mutation.ClearAssetCategory()
	return _u
}

// ClearAssetType clears the "asset_type" edge to the AssetType entity.
func (_u *AssetsUpdate) ClearAssetType() *AssetsUpdate {
	_u.mutation.ClearAssetType()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *AssetsUpdate) ClearOrganization() *AssetsUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(assets.Table, assets.Columns, sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetName(); ok {
		_spec.SetField(assets.FieldAssetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetCode(); ok {
		_spec.SetField(assets.FieldAssetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetDescription(); ok {
		_spec.SetField(assets.FieldAssetDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetFlag(); ok {
		_spec.SetField(assets.FieldAssetFlag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(assets.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(assets.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(assets.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchasePrice(); ok {
		_spec.SetField(assets.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPurchasePrice(); ok {
		_spec.AddField(assets.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DepreciationPrice(); ok {
		_spec.SetField(assets.FieldDepreciationPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDepreciationPrice(); ok {
		_spec.AddField(assets.FieldDepreciationPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PurchaseDate(); ok {
		_spec.SetField(assets.FieldPurchaseDate, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(assets.FieldPurchaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Manufacturer(); ok {
		_spec.SetField(assets.FieldManufacturer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(assets.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtherMetadata(); ok {
		_spec.SetField(assets.FieldOtherMetadata, field.TypeJSON, value)
	}
	if _u.mutation.OtherMetadataCleared() {
		_spec.ClearField(assets.FieldOtherMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(assets.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assets.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(assets.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AssetCategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetCategoryTable,
			Columns: []string{assets.AssetCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetCategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetCategoryTable,
			Columns: []string{assets.AssetCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetTypeTable,
			Columns: []string{assets.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetTypeTable,
			Columns: []string{assets.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.OrganizationTable,
			Columns: []string{assets.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.OrganizationTable,
			Columns: []string{assets.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Assets
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assets.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetsUpdateOne is the builder for updating a single Assets entity.
type AssetsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetsMutation
}

// SetAssetName sets the "asset_name" field.
func (_u *AssetsUpdateOne) SetAssetName(v string) *AssetsUpdateOne {
	_u.mutation.SetAssetName(v)
	return _u
}

// SetNillableAssetName sets the "asset_name" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetName(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetName(*v)
	}
	return _u
}

// SetAssetCode sets the "asset_code" field.
func (_u *AssetsUpdateOne) SetAssetCode(v string) *AssetsUpdateOne {
	_u.mutation.SetAssetCode(v)
	return _u
}

// SetNillableAssetCode sets the "asset_code" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetCode(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetCode(*v)
	}
	return _u
}

// SetAssetDescription sets the "asset_description" field.
func (_u *AssetsUpdateOne) SetAssetDescription(v string) *AssetsUpdateOne {
	_u.mutation.SetAssetDescription(v)
	return _u
}

// SetNillableAssetDescription sets the "asset_description" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetDescription(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetDescription(*v)
	}
	return _u
}

// SetAssetFlag sets the "asset_flag" field.
func (_u *AssetsUpdateOne) SetAssetFlag(v string) *AssetsUpdateOne {
	_u.mutation.SetAssetFlag(v)
	return _u
}

// SetNillableAssetFlag sets the "asset_flag" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetFlag(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetFlag(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *AssetsUpdateOne) SetQuantity(v int) *AssetsUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableQuantity(v *int) *AssetsUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *AssetsUpdateOne) AddQuantity(v int) *AssetsUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetLocation sets the "location" field.
func (_u *AssetsUpdateOne) SetLocation(v string) *AssetsUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableLocation(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetPurchasePrice sets the "purchase_price" field.
func (_u *AssetsUpdateOne) SetPurchasePrice(v float64) *AssetsUpdateOne {
	_u.mutation.ResetPurchasePrice()
	_u.mutation.SetPurchasePrice(v)
	return _u
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillablePurchasePrice(v *float64) *AssetsUpdateOne {
	if v != nil {
		_u.SetPurchasePrice(*v)
	}
	return _u
}

// AddPurchasePrice adds value to the "purchase_price" field.
func (_u *AssetsUpdateOne) AddPurchasePrice(v float64) *AssetsUpdateOne {
	_u.mutation.AddPurchasePrice(v)
	return _u
}

// SetDepreciationPrice sets the "depreciation_price" field.
func (_u *AssetsUpdateOne) SetDepreciationPrice(v float64) *AssetsUpdateOne {
	_u.mutation.ResetDepreciationPrice()
	_u.mutation.SetDepreciationPrice(v)
	return _u
}

// SetNillableDepreciationPrice sets the "depreciation_price" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableDepreciationPrice(v *float64) *AssetsUpdateOne {
	if v != nil {
		_u.SetDepreciationPrice(*v)
	}
	return _u
}

// AddDepreciationPrice adds value to the "depreciation_price" field.
func (_u *AssetsUpdateOne) AddDepreciationPrice(v float64) *AssetsUpdateOne {
	_u.mutation.AddDepreciationPrice(v)
	return _u
}

// SetPurchaseDate sets the "purchase_date" field.
func (_u *AssetsUpdateOne) SetPurchaseDate(v time.Time) *AssetsUpdateOne {
	_u.mutation.SetPurchaseDate(v)
	return _u
}

// SetNillablePurchaseDate sets the "purchase_date" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillablePurchaseDate(v *time.Time) *AssetsUpdateOne {
	if v != nil {
		_u.SetPurchaseDate(*v)
	}
	return _u
}

// ClearPurchaseDate clears the value of the "purchase_date" field.
func (_u *AssetsUpdateOne) ClearPurchaseDate() *AssetsUpdateOne {
	_u.mutation.ClearPurchaseDate()
	return _u
}

// SetManufacturer sets the "manufacturer" field.
func (_u *AssetsUpdateOne) SetManufacturer(v string) *AssetsUpdateOne {
	_u.mutation.SetManufacturer(v)
	return _u
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableManufacturer(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetManufacturer(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AssetsUpdateOne) SetModel(v string) *AssetsUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableModel(v *string) *AssetsUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOtherMetadata sets the "other_metadata" field.
func (_u *AssetsUpdateOne) SetOtherMetadata(v map[string]interface{}) *AssetsUpdateOne {
	_u.mutation.SetOtherMetadata(v)
	return _u
}

// ClearOtherMetadata clears the value of the "other_metadata" field.
func (_u *AssetsUpdateOne) ClearOtherMetadata() *AssetsUpdateOne {
	_u.mutation.ClearOtherMetadata()
	return _u
}

// SetAssetTypeID sets the "asset_type_id" field.
func (_u *AssetsUpdateOne) SetAssetTypeID(v uuid.UUID) *AssetsUpdateOne {
	_u.mutation.SetAssetTypeID(v)
	return _u
}

// SetNillableAssetTypeID sets the "asset_type_id" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetTypeID(v *uuid.UUID) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetTypeID(*v)
	}
	return _u
}

// ClearAssetTypeID clears the value of the "asset_type_id" field.
func (_u *AssetsUpdateOne) ClearAssetTypeID() *AssetsUpdateOne {
	_u.mutation.ClearAssetTypeID()
	return _u
}

// SetAssetCategoryID sets the "asset_category_id" field.
func (_u *AssetsUpdateOne) SetAssetCategoryID(v uuid.UUID) *AssetsUpdateOne {
	_u.mutation.SetAssetCategoryID(v)
	return _u
}

// SetNillableAssetCategoryID sets the "asset_category_id" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableAssetCategoryID(v *uuid.UUID) *AssetsUpdateOne {
	if v != nil {
		_u.SetAssetCategoryID(*v)
	}
	return _u
}

// ClearAssetCategoryID clears the value of the "asset_category_id" field.
func (_u *AssetsUpdateOne) ClearAssetCategoryID() *AssetsUpdateOne {
	_u.mutation.ClearAssetCategoryID()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *AssetsUpdateOne) SetOrganizationID(v uuid.UUID) *AssetsUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *AssetsUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *AssetsUpdateOne) ClearOrganizationID() *AssetsUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetsUpdateOne) SetCreatedAt(v time.Time) *AssetsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableCreatedAt(v *time.Time) *AssetsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetsUpdateOne) SetUpdatedAt(v time.Time) *AssetsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AssetsUpdateOne) SetNillableUpdatedAt(v *time.Time) *AssetsUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AssetsUpdateOne) ClearUpdatedAt() *AssetsUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetAssetCategory sets the "asset_category" edge to the AssetCategory entity.
func (_u *AssetsUpdateOne) SetAssetCategory(v *AssetCategory) *AssetsUpdateOne {
	return _u.SetAssetCategoryID(v.ID)
}

// SetAssetType sets the "asset_type" edge to the AssetType entity.
func (_u *AssetsUpdateOne) SetAssetType(v *AssetType) *AssetsUpdateOne {
	return _u.SetAssetTypeID(v.ID)
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *AssetsUpdateOne) SetOrganization(v *Organization) *AssetsUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// Mutation returns the AssetsMutation object of the builder.
func (_u *AssetsUpdateOne) Mutation() *AssetsMutation {
	return _u.mutation
}

// ClearAssetCategory clears the "asset_category" edge to the AssetCategory entity.
func (_u *AssetsUpdateOne) ClearAssetCategory() *AssetsUpdateOne {
	_u.mutation.ClearAssetCategory()
	return _u
}

// ClearAssetType clears the "asset_type" edge to the AssetType entity.
func (_u *AssetsUpdateOne) ClearAssetType() *AssetsUpdateOne {
	_u.mutation.ClearAssetType()
	return _u
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *AssetsUpdateOne) ClearOrganization() *AssetsUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// Where appends a list predicates to the AssetsUpdate builder.
func (_u *AssetsUpdateOne) Where(ps ...predicate.Assets) *AssetsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetsUpdateOne) Select(field string, fields ...string) *AssetsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Assets entity.
func (_u *AssetsUpdateOne) Save(ctx context.Context) (*Assets, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetsUpdateOne) SaveX(ctx context.Context) *Assets {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetsUpdateOne) sqlSave(ctx context.Context) (_node *Assets, err error) {
	_spec := sqlgraph.NewUpdateSpec(assets.Table, assets.Columns, sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Assets.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assets.FieldID)
		for _, f := range fields {
			if !assets.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assets.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetName(); ok {
		_spec.SetField(assets.FieldAssetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetCode(); ok {
		_spec.SetField(assets.FieldAssetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetDescription(); ok {
		_spec.SetField(assets.FieldAssetDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetFlag(); ok {
		_spec.SetField(assets.FieldAssetFlag, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(assets.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(assets.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(assets.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchasePrice(); ok {
		_spec.SetField(assets.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPurchasePrice(); ok {
		_spec.AddField(assets.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DepreciationPrice(); ok {
		_spec.SetField(assets.FieldDepreciationPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDepreciationPrice(); ok {
		_spec.AddField(assets.FieldDepreciationPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PurchaseDate(); ok {
		_spec.SetField(assets.FieldPurchaseDate, field.TypeTime, value)
	}
	if _u.mutation.PurchaseDateCleared() {
		_spec.ClearField(assets.FieldPurchaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Manufacturer(); ok {
		_spec.SetField(assets.FieldManufacturer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(assets.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtherMetadata(); ok {
		_spec.SetField(assets.FieldOtherMetadata, field.TypeJSON, value)
	}
	if _u.mutation.OtherMetadataCleared() {
		_spec.ClearField(assets.FieldOtherMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(assets.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assets.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(assets.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AssetCategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetCategoryTable,
			Columns: []string{assets.AssetCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetCategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetCategoryTable,
			Columns: []string{assets.AssetCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetTypeTable,
			Columns: []string{assets.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.AssetTypeTable,
			Columns: []string{assets.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.OrganizationTable,
			Columns: []string{assets.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assets.OrganizationTable,
			Columns: []string{assets.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Assets
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Assets{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assets.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
