// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moon/ent/assetcategory"
	"moon/ent/assets"
	"moon/ent/assettype"
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// AssetCategoryUpdate is the builder for updating AssetCategory entities.
type AssetCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *AssetCategoryMutation
}

// Where appends a list predicates to the AssetCategoryUpdate builder.
func (_u *AssetCategoryUpdate) Where(ps ...predicate.AssetCategory) *AssetCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategoryName sets the "category_name" field.
func (_u *AssetCategoryUpdate) SetCategoryName(v string) *AssetCategoryUpdate {
	_u.mutation.SetCategoryName(v)
	return _u
}

// SetNillableCategoryName sets the "category_name" field if the given value is not nil.
func (_u *AssetCategoryUpdate) SetNillableCategoryName(v *string) *AssetCategoryUpdate {
	if v != nil {
		_u.SetCategoryName(*v)
	}
	return _u
}

// SetCategoryCode sets the "category_code" field.
func (_u *AssetCategoryUpdate) SetCategoryCode(v string) *AssetCategoryUpdate {
	_u.mutation.SetCategoryCode(v)
	return _u
}

// SetNillableCategoryCode sets the "category_code" field if the given value is not nil.
func (_u *AssetCategoryUpdate) SetNillableCategoryCode(v *string) *AssetCategoryUpdate {
	if v != nil {
		_u.SetCategoryCode(*v)
	}
	return _u
}

// SetCategoryFlag sets the "category_flag" field.
func (_u *AssetCategoryUpdate) SetCategoryFlag(v string) *AssetCategoryUpdate {
	_u.mutation.SetCategoryFlag(v)
	return _u
}

// SetNillableCategoryFlag sets the "category_flag" field if the given value is not nil.
func (_u *AssetCategoryUpdate) SetNillableCategoryFlag(v *string) *AssetCategoryUpdate {
	if v != nil {
		_u.SetCategoryFlag(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetCategoryUpdate) SetCreatedAt(v time.Time) *AssetCategoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetCategoryUpdate) SetNillableCreatedAt(v *time.Time) *AssetCategoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetCategoryUpdate) SetUpdatedAt(v time.Time) *AssetCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AssetCategoryUpdate) SetNillableUpdatedAt(v *time.Time) *AssetCategoryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AssetCategoryUpdate) ClearUpdatedAt() *AssetCategoryUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddAssetTypeIDs adds the "asset_type" edge to the AssetType entity by IDs.
func (_u *AssetCategoryUpdate) AddAssetTypeIDs(ids ...uuid.UUID) *AssetCategoryUpdate {
	_u.mutation.AddAssetTypeIDs(ids...)
	return _u
}

// AddAssetType adds the "asset_type" edges to the AssetType entity.
func (_u *AssetCategoryUpdate) AddAssetType(v ...*AssetType) *AssetCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetTypeIDs(ids...)
}

// AddAssetIDs adds the "asset" edge to the Assets entity by IDs.
func (_u *AssetCategoryUpdate) AddAssetIDs(ids ...uuid.UUID) *AssetCategoryUpdate {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAsset adds the "asset" edges to the Assets entity.
func (_u *AssetCategoryUpdate) AddAsset(v ...*Assets) *AssetCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the AssetCategoryMutation object of the builder.
func (_u *AssetCategoryUpdate) Mutation() *AssetCategoryMutation {
	return _u.mutation
}

// ClearAssetType clears all "asset_type" edges to the AssetType entity.
func (_u *AssetCategoryUpdate) ClearAssetType() *AssetCategoryUpdate {
	_u.mutation.ClearAssetType()
	return _u
}

// RemoveAssetTypeIDs removes the "asset_type" edge to AssetType entities by IDs.
func (_u *AssetCategoryUpdate) RemoveAssetTypeIDs(ids ...uuid.UUID) *AssetCategoryUpdate {
	_u.mutation.RemoveAssetTypeIDs(ids...)
	return _u
}

// RemoveAssetType removes "asset_type" edges to AssetType entities.
func (_u *AssetCategoryUpdate) RemoveAssetType(v ...*AssetType) *AssetCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetTypeIDs(ids...)
}

// ClearAsset clears all "asset" edges to the Assets entity.
func (_u *AssetCategoryUpdate) ClearAsset() *AssetCategoryUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// RemoveAssetIDs removes the "asset" edge to Assets entities by IDs.
func (_u *AssetCategoryUpdate) RemoveAssetIDs(ids ...uuid.UUID) *AssetCategoryUpdate {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAsset removes "asset" edges to Assets entities.
func (_u *AssetCategoryUpdate) RemoveAsset(v ...*Assets) *AssetCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetCategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(assetcategory.Table, assetcategory.Columns, sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CategoryName(); ok {
		_spec.SetField(assetcategory.FieldCategoryName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryCode(); ok {
		_spec.SetField(assetcategory.FieldCategoryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryFlag(); ok {
		_spec.SetField(assetcategory.FieldCategoryFlag, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(assetcategory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assetcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(assetcategory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetTypeIDs(); len(nodes) > 0 && !_u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetIDs(); len(nodes) > 0 && !_u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AssetCategory
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetCategoryUpdateOne is the builder for updating a single AssetCategory entity.
type AssetCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetCategoryMutation
}

// SetCategoryName sets the "category_name" field.
func (_u *AssetCategoryUpdateOne) SetCategoryName(v string) *AssetCategoryUpdateOne {
	_u.mutation.SetCategoryName(v)
	return _u
}

// SetNillableCategoryName sets the "category_name" field if the given value is not nil.
func (_u *AssetCategoryUpdateOne) SetNillableCategoryName(v *string) *AssetCategoryUpdateOne {
	if v != nil {
		_u.SetCategoryName(*v)
	}
	return _u
}

// SetCategoryCode sets the "category_code" field.
func (_u *AssetCategoryUpdateOne) SetCategoryCode(v string) *AssetCategoryUpdateOne {
	_u.mutation.SetCategoryCode(v)
	return _u
}

// SetNillableCategoryCode sets the "category_code" field if the given value is not nil.
func (_u *AssetCategoryUpdateOne) SetNillableCategoryCode(v *string) *AssetCategoryUpdateOne {
	if v != nil {
		_u.SetCategoryCode(*v)
	}
	return _u
}

// SetCategoryFlag sets the "category_flag" field.
func (_u *AssetCategoryUpdateOne) SetCategoryFlag(v string) *AssetCategoryUpdateOne {
	_u.mutation.SetCategoryFlag(v)
	return _u
}

// SetNillableCategoryFlag sets the "category_flag" field if the given value is not nil.
func (_u *AssetCategoryUpdateOne) SetNillableCategoryFlag(v *string) *AssetCategoryUpdateOne {
	if v != nil {
		_u.SetCategoryFlag(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetCategoryUpdateOne) SetCreatedAt(v time.Time) *AssetCategoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetCategoryUpdateOne) SetNillableCreatedAt(v *time.Time) *AssetCategoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetCategoryUpdateOne) SetUpdatedAt(v time.Time) *AssetCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AssetCategoryUpdateOne) SetNillableUpdatedAt(v *time.Time) *AssetCategoryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AssetCategoryUpdateOne) ClearUpdatedAt() *AssetCategoryUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddAssetTypeIDs adds the "asset_type" edge to the AssetType entity by IDs.
func (_u *AssetCategoryUpdateOne) AddAssetTypeIDs(ids ...uuid.UUID) *AssetCategoryUpdateOne {
	_u.mutation.AddAssetTypeIDs(ids...)
	return _u
}

// AddAssetType adds the "asset_type" edges to the AssetType entity.
func (_u *AssetCategoryUpdateOne) AddAssetType(v ...*AssetType) *AssetCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetTypeIDs(ids...)
}

// AddAssetIDs adds the "asset" edge to the Assets entity by IDs.
func (_u *AssetCategoryUpdateOne) AddAssetIDs(ids ...uuid.UUID) *AssetCategoryUpdateOne {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAsset adds the "asset" edges to the Assets entity.
func (_u *AssetCategoryUpdateOne) AddAsset(v ...*Assets) *AssetCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the AssetCategoryMutation object of the builder.
func (_u *AssetCategoryUpdateOne) Mutation() *AssetCategoryMutation {
	return _u.mutation
}

// ClearAssetType clears all "asset_type" edges to the AssetType entity.
func (_u *AssetCategoryUpdateOne) ClearAssetType() *AssetCategoryUpdateOne {
	_u.mutation.ClearAssetType()
	return _u
}

// RemoveAssetTypeIDs removes the "asset_type" edge to AssetType entities by IDs.
func (_u *AssetCategoryUpdateOne) RemoveAssetTypeIDs(ids ...uuid.UUID) *AssetCategoryUpdateOne {
	_u.mutation.RemoveAssetTypeIDs(ids...)
	return _u
}

// RemoveAssetType removes "asset_type" edges to AssetType entities.
func (_u *AssetCategoryUpdateOne) RemoveAssetType(v ...*AssetType) *AssetCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetTypeIDs(ids...)
}

// ClearAsset clears all "asset" edges to the Assets entity.
func (_u *AssetCategoryUpdateOne) ClearAsset() *AssetCategoryUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// RemoveAssetIDs removes the "asset" edge to Assets entities by IDs.
func (_u *AssetCategoryUpdateOne) RemoveAssetIDs(ids ...uuid.UUID) *AssetCategoryUpdateOne {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAsset removes "asset" edges to Assets entities.
func (_u *AssetCategoryUpdateOne) RemoveAsset(v ...*Assets) *AssetCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Where appends a list predicates to the AssetCategoryUpdate builder.
func (_u *AssetCategoryUpdateOne) Where(ps ...predicate.AssetCategory) *AssetCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetCategoryUpdateOne) Select(field string, fields ...string) *AssetCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AssetCategory entity.
func (_u *AssetCategoryUpdateOne) Save(ctx context.Context) (*AssetCategory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetCategoryUpdateOne) SaveX(ctx context.Context) *AssetCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetCategoryUpdateOne) sqlSave(ctx context.Context) (_node *AssetCategory, err error) {
	_spec := sqlgraph.NewUpdateSpec(assetcategory.Table, assetcategory.Columns, sqlgraph.NewFieldSpec(assetcategory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssetCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetcategory.FieldID)
		for _, f := range fields {
			if !assetcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assetcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CategoryName(); ok {
		_spec.SetField(assetcategory.FieldCategoryName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryCode(); ok {
		_spec.SetField(assetcategory.FieldCategoryCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoryFlag(); ok {
		_spec.SetField(assetcategory.FieldCategoryFlag, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(assetcategory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(assetcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(assetcategory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetTypeIDs(); len(nodes) > 0 && !_u.mutation.AssetTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTypeTable,
			Columns: []string{assetcategory.AssetTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assettype.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.AssetType
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetIDs(); len(nodes) > 0 && !_u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetcategory.AssetTable,
			Columns: []string{assetcategory.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assets.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Assets
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AssetCategory
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &AssetCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
