// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"moon/ent/assetcategory"
	"moon/ent/assets"
	"moon/ent/assettype"
	"moon/ent/llmmodel"
	"moon/ent/llmprocurementanalysis"
	"moon/ent/llmtokenusage"
	"moon/ent/organization"
	"moon/ent/permission"
	"moon/ent/procurementacceptance"
	"moon/ent/procurementexpert"
	"moon/ent/procurementfraudrisk"
	"moon/ent/procurementimplementation"
	"moon/ent/procurementplan"
	"moon/ent/procurementplantype"
	"moon/ent/procurementreview"
	"moon/ent/role"
	"moon/ent/user"

	"entgo.io/contrib/entgql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/hashicorp/go-multierror"
)

// Noder wraps the basic Node method.
type Noder interface {
	IsNode()
}

var assetcategoryImplementors = []string{"AssetCategory", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*AssetCategory) IsNode() {}

var assettypeImplementors = []string{"AssetType", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*AssetType) IsNode() {}

var assetsImplementors = []string{"Assets", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Assets) IsNode() {}

var llmmodelImplementors = []string{"LlmModel", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*LlmModel) IsNode() {}

var llmprocurementanalysisImplementors = []string{"LlmProcurementAnalysis", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*LlmProcurementAnalysis) IsNode() {}

var llmtokenusageImplementors = []string{"LlmTokenUsage", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*LlmTokenUsage) IsNode() {}

var organizationImplementors = []string{"Organization", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Organization) IsNode() {}

var permissionImplementors = []string{"Permission", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Permission) IsNode() {}

var procurementacceptanceImplementors = []string{"ProcurementAcceptance", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementAcceptance) IsNode() {}

var procurementexpertImplementors = []string{"ProcurementExpert", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementExpert) IsNode() {}

var procurementfraudriskImplementors = []string{"ProcurementFraudRisk", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementFraudRisk) IsNode() {}

var procurementimplementationImplementors = []string{"ProcurementImplementation", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementImplementation) IsNode() {}

var procurementplanImplementors = []string{"ProcurementPlan", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementPlan) IsNode() {}

var procurementplantypeImplementors = []string{"ProcurementPlanType", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementPlanType) IsNode() {}

var procurementreviewImplementors = []string{"ProcurementReview", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*ProcurementReview) IsNode() {}

var roleImplementors = []string{"Role", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*Role) IsNode() {}

var userImplementors = []string{"User", "Node"}

// IsNode implements the Node interface check for GQLGen.
func (*User) IsNode() {}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, uuid.UUID) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, uuid.UUID) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, uuid.UUID) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id uuid.UUID) (string, error) {
			return "", fmt.Errorf("cannot resolve noder (%v) without its type", id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//	c.Noder(ctx, id)
//	c.Noder(ctx, id, ent.WithNodeType(typeResolver))
func (c *Client) Noder(ctx context.Context, id uuid.UUID, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id uuid.UUID) (Noder, error) {
	switch table {
	case assetcategory.Table:
		query := c.AssetCategory.Query().
			Where(assetcategory.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, assetcategoryImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case assettype.Table:
		query := c.AssetType.Query().
			Where(assettype.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, assettypeImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case assets.Table:
		query := c.Assets.Query().
			Where(assets.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, assetsImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case llmmodel.Table:
		query := c.LlmModel.Query().
			Where(llmmodel.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, llmmodelImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case llmprocurementanalysis.Table:
		query := c.LlmProcurementAnalysis.Query().
			Where(llmprocurementanalysis.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, llmprocurementanalysisImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case llmtokenusage.Table:
		query := c.LlmTokenUsage.Query().
			Where(llmtokenusage.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, llmtokenusageImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case organization.Table:
		query := c.Organization.Query().
			Where(organization.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, organizationImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case permission.Table:
		query := c.Permission.Query().
			Where(permission.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, permissionImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementacceptance.Table:
		query := c.ProcurementAcceptance.Query().
			Where(procurementacceptance.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementacceptanceImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementexpert.Table:
		query := c.ProcurementExpert.Query().
			Where(procurementexpert.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementexpertImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementfraudrisk.Table:
		query := c.ProcurementFraudRisk.Query().
			Where(procurementfraudrisk.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementfraudriskImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementimplementation.Table:
		query := c.ProcurementImplementation.Query().
			Where(procurementimplementation.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementimplementationImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementplan.Table:
		query := c.ProcurementPlan.Query().
			Where(procurementplan.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementplanImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementplantype.Table:
		query := c.ProcurementPlanType.Query().
			Where(procurementplantype.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementplantypeImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case procurementreview.Table:
		query := c.ProcurementReview.Query().
			Where(procurementreview.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, procurementreviewImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case role.Table:
		query := c.Role.Query().
			Where(role.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, roleImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	case user.Table:
		query := c.User.Query().
			Where(user.ID(id))
		if fc := graphql.GetFieldContext(ctx); fc != nil {
			if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, userImplementors...); err != nil {
				return nil, err
			}
		}
		return query.Only(ctx)
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []uuid.UUID, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]uuid.UUID)
	id2idx := make(map[uuid.UUID][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []uuid.UUID) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[uuid.UUID][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case assetcategory.Table:
		query := c.AssetCategory.Query().
			Where(assetcategory.IDIn(ids...))
		query, err := query.CollectFields(ctx, assetcategoryImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case assettype.Table:
		query := c.AssetType.Query().
			Where(assettype.IDIn(ids...))
		query, err := query.CollectFields(ctx, assettypeImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case assets.Table:
		query := c.Assets.Query().
			Where(assets.IDIn(ids...))
		query, err := query.CollectFields(ctx, assetsImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case llmmodel.Table:
		query := c.LlmModel.Query().
			Where(llmmodel.IDIn(ids...))
		query, err := query.CollectFields(ctx, llmmodelImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case llmprocurementanalysis.Table:
		query := c.LlmProcurementAnalysis.Query().
			Where(llmprocurementanalysis.IDIn(ids...))
		query, err := query.CollectFields(ctx, llmprocurementanalysisImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case llmtokenusage.Table:
		query := c.LlmTokenUsage.Query().
			Where(llmtokenusage.IDIn(ids...))
		query, err := query.CollectFields(ctx, llmtokenusageImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case organization.Table:
		query := c.Organization.Query().
			Where(organization.IDIn(ids...))
		query, err := query.CollectFields(ctx, organizationImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case permission.Table:
		query := c.Permission.Query().
			Where(permission.IDIn(ids...))
		query, err := query.CollectFields(ctx, permissionImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementacceptance.Table:
		query := c.ProcurementAcceptance.Query().
			Where(procurementacceptance.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementacceptanceImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementexpert.Table:
		query := c.ProcurementExpert.Query().
			Where(procurementexpert.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementexpertImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementfraudrisk.Table:
		query := c.ProcurementFraudRisk.Query().
			Where(procurementfraudrisk.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementfraudriskImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementimplementation.Table:
		query := c.ProcurementImplementation.Query().
			Where(procurementimplementation.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementimplementationImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementplan.Table:
		query := c.ProcurementPlan.Query().
			Where(procurementplan.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementplanImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementplantype.Table:
		query := c.ProcurementPlanType.Query().
			Where(procurementplantype.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementplantypeImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case procurementreview.Table:
		query := c.ProcurementReview.Query().
			Where(procurementreview.IDIn(ids...))
		query, err := query.CollectFields(ctx, procurementreviewImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case role.Table:
		query := c.Role.Query().
			Where(role.IDIn(ids...))
		query, err := query.CollectFields(ctx, roleImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case user.Table:
		query := c.User.Query().
			Where(user.IDIn(ids...))
		query, err := query.CollectFields(ctx, userImplementors...)
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}
