// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"moon/ent/llmprocurementanalysis"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// LlmProcurementAnalysis is the model entity for the LlmProcurementAnalysis schema.
type LlmProcurementAnalysis struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID *uuid.UUID `json:"model_id,omitempty"`
	// ProcurementPlanID holds the value of the "procurement_plan_id" field.
	ProcurementPlanID *uuid.UUID `json:"procurement_plan_id,omitempty"`
	// ProcurementImplementationID holds the value of the "procurement_implementation_id" field.
	ProcurementImplementationID *uuid.UUID `json:"procurement_implementation_id,omitempty"`
	// AnalysisResult holds the value of the "analysis_result" field.
	AnalysisResult *string `json:"analysis_result,omitempty"`
	// TokenUsageID holds the value of the "token_usage_id" field.
	TokenUsageID *uuid.UUID `json:"token_usage_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LlmProcurementAnalysis) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case llmprocurementanalysis.FieldModelID, llmprocurementanalysis.FieldProcurementPlanID, llmprocurementanalysis.FieldProcurementImplementationID, llmprocurementanalysis.FieldTokenUsageID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case llmprocurementanalysis.FieldAnalysisResult:
			values[i] = new(sql.NullString)
		case llmprocurementanalysis.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case llmprocurementanalysis.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LlmProcurementAnalysis fields.
func (_m *LlmProcurementAnalysis) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case llmprocurementanalysis.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case llmprocurementanalysis.FieldModelID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(uuid.UUID)
				*_m.ModelID = *value.S.(*uuid.UUID)
			}
		case llmprocurementanalysis.FieldProcurementPlanID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field procurement_plan_id", values[i])
			} else if value.Valid {
				_m.ProcurementPlanID = new(uuid.UUID)
				*_m.ProcurementPlanID = *value.S.(*uuid.UUID)
			}
		case llmprocurementanalysis.FieldProcurementImplementationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field procurement_implementation_id", values[i])
			} else if value.Valid {
				_m.ProcurementImplementationID = new(uuid.UUID)
				*_m.ProcurementImplementationID = *value.S.(*uuid.UUID)
			}
		case llmprocurementanalysis.FieldAnalysisResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field analysis_result", values[i])
			} else if value.Valid {
				_m.AnalysisResult = new(string)
				*_m.AnalysisResult = value.String
			}
		case llmprocurementanalysis.FieldTokenUsageID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field token_usage_id", values[i])
			} else if value.Valid {
				_m.TokenUsageID = new(uuid.UUID)
				*_m.TokenUsageID = *value.S.(*uuid.UUID)
			}
		case llmprocurementanalysis.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LlmProcurementAnalysis.
// This includes values selected through modifiers, order, etc.
func (_m *LlmProcurementAnalysis) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LlmProcurementAnalysis.
// Note that you need to call LlmProcurementAnalysis.Unwrap() before calling this method if this LlmProcurementAnalysis
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LlmProcurementAnalysis) Update() *LlmProcurementAnalysisUpdateOne {
	return NewLlmProcurementAnalysisClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LlmProcurementAnalysis entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LlmProcurementAnalysis) Unwrap() *LlmProcurementAnalysis {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LlmProcurementAnalysis is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LlmProcurementAnalysis) String() string {
	var builder strings.Builder
	builder.WriteString("LlmProcurementAnalysis(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProcurementPlanID; v != nil {
		builder.WriteString("procurement_plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProcurementImplementationID; v != nil {
		builder.WriteString("procurement_implementation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AnalysisResult; v != nil {
		builder.WriteString("analysis_result=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenUsageID; v != nil {
		builder.WriteString("token_usage_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LlmProcurementAnalyses is a parsable slice of LlmProcurementAnalysis.
type LlmProcurementAnalyses []*LlmProcurementAnalysis
