// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moon/ent/llmtokenusage"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// LlmTokenUsageCreate is the builder for creating a LlmTokenUsage entity.
type LlmTokenUsageCreate struct {
	config
	mutation *LlmTokenUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelID sets the "model_id" field.
func (_c *LlmTokenUsageCreate) SetModelID(v uuid.UUID) *LlmTokenUsageCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LlmTokenUsageCreate) SetUserID(v uuid.UUID) *LlmTokenUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableUserID(v *uuid.UUID) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *LlmTokenUsageCreate) SetPromptTokens(v int) *LlmTokenUsageCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillablePromptTokens(v *int) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *LlmTokenUsageCreate) SetCompletionTokens(v int) *LlmTokenUsageCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableCompletionTokens(v *int) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *LlmTokenUsageCreate) SetTotalTokens(v int) *LlmTokenUsageCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableTotalTokens(v *int) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetCostAmount sets the "cost_amount" field.
func (_c *LlmTokenUsageCreate) SetCostAmount(v float64) *LlmTokenUsageCreate {
	_c.mutation.SetCostAmount(v)
	return _c
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableCostAmount(v *float64) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetCostAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LlmTokenUsageCreate) SetCreatedAt(v time.Time) *LlmTokenUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableCreatedAt(v *time.Time) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LlmTokenUsageCreate) SetID(v uuid.UUID) *LlmTokenUsageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LlmTokenUsageCreate) SetNillableID(v *uuid.UUID) *LlmTokenUsageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LlmTokenUsageMutation object of the builder.
func (_c *LlmTokenUsageCreate) Mutation() *LlmTokenUsageMutation {
	return _c.mutation
}

// Save creates the LlmTokenUsage in the database.
func (_c *LlmTokenUsageCreate) Save(ctx context.Context) (*LlmTokenUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LlmTokenUsageCreate) SaveX(ctx context.Context) *LlmTokenUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LlmTokenUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LlmTokenUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LlmTokenUsageCreate) defaults() {
	if _, ok := _c.mutation.PromptTokens(); !ok {
		v := llmtokenusage.DefaultPromptTokens
		_c.mutation.SetPromptTokens(v)
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		v := llmtokenusage.DefaultCompletionTokens
		_c.mutation.SetCompletionTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := llmtokenusage.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.CostAmount(); !ok {
		v := llmtokenusage.DefaultCostAmount
		_c.mutation.SetCostAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := llmtokenusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := llmtokenusage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LlmTokenUsageCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "LlmTokenUsage.model_id"`)}
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		return &ValidationError{Name: "prompt_tokens", err: errors.New(`ent: missing required field "LlmTokenUsage.prompt_tokens"`)}
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		return &ValidationError{Name: "completion_tokens", err: errors.New(`ent: missing required field "LlmTokenUsage.completion_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "LlmTokenUsage.total_tokens"`)}
	}
	if _, ok := _c.mutation.CostAmount(); !ok {
		return &ValidationError{Name: "cost_amount", err: errors.New(`ent: missing required field "LlmTokenUsage.cost_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LlmTokenUsage.created_at"`)}
	}
	return nil
}

func (_c *LlmTokenUsageCreate) sqlSave(ctx context.Context) (*LlmTokenUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LlmTokenUsageCreate) createSpec() (*LlmTokenUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &LlmTokenUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(llmtokenusage.Table, sqlgraph.NewFieldSpec(llmtokenusage.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.LlmTokenUsage
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(llmtokenusage.FieldModelID, field.TypeUUID, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(llmtokenusage.FieldUserID, field.TypeUUID, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(llmtokenusage.FieldPromptTokens, field.TypeInt, value)
		_node.PromptTokens = value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(llmtokenusage.FieldCompletionTokens, field.TypeInt, value)
		_node.CompletionTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(llmtokenusage.FieldTotalTokens, field.TypeInt, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.CostAmount(); ok {
		_spec.SetField(llmtokenusage.FieldCostAmount, field.TypeFloat64, value)
		_node.CostAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(llmtokenusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LlmTokenUsage.Create().
//		SetModelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LlmTokenUsageUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *LlmTokenUsageCreate) OnConflict(opts ...sql.ConflictOption) *LlmTokenUsageUpsertOne {
	_c.conflict = opts
	return &LlmTokenUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LlmTokenUsageCreate) OnConflictColumns(columns ...string) *LlmTokenUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LlmTokenUsageUpsertOne{
		create: _c,
	}
}

type (
	// LlmTokenUsageUpsertOne is the builder for "upsert"-ing
	//  one LlmTokenUsage node.
	LlmTokenUsageUpsertOne struct {
		create *LlmTokenUsageCreate
	}

	// LlmTokenUsageUpsert is the "OnConflict" setter.
	LlmTokenUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelID sets the "model_id" field.
func (u *LlmTokenUsageUpsert) SetModelID(v uuid.UUID) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateModelID() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldModelID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LlmTokenUsageUpsert) SetUserID(v uuid.UUID) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateUserID() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *LlmTokenUsageUpsert) ClearUserID() *LlmTokenUsageUpsert {
	u.SetNull(llmtokenusage.FieldUserID)
	return u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *LlmTokenUsageUpsert) SetPromptTokens(v int) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldPromptTokens, v)
	return u
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdatePromptTokens() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldPromptTokens)
	return u
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *LlmTokenUsageUpsert) AddPromptTokens(v int) *LlmTokenUsageUpsert {
	u.Add(llmtokenusage.FieldPromptTokens, v)
	return u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *LlmTokenUsageUpsert) SetCompletionTokens(v int) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldCompletionTokens, v)
	return u
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateCompletionTokens() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldCompletionTokens)
	return u
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *LlmTokenUsageUpsert) AddCompletionTokens(v int) *LlmTokenUsageUpsert {
	u.Add(llmtokenusage.FieldCompletionTokens, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *LlmTokenUsageUpsert) SetTotalTokens(v int) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateTotalTokens() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *LlmTokenUsageUpsert) AddTotalTokens(v int) *LlmTokenUsageUpsert {
	u.Add(llmtokenusage.FieldTotalTokens, v)
	return u
}

// SetCostAmount sets the "cost_amount" field.
func (u *LlmTokenUsageUpsert) SetCostAmount(v float64) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldCostAmount, v)
	return u
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateCostAmount() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldCostAmount)
	return u
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *LlmTokenUsageUpsert) AddCostAmount(v float64) *LlmTokenUsageUpsert {
	u.Add(llmtokenusage.FieldCostAmount, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LlmTokenUsageUpsert) SetCreatedAt(v time.Time) *LlmTokenUsageUpsert {
	u.Set(llmtokenusage.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LlmTokenUsageUpsert) UpdateCreatedAt() *LlmTokenUsageUpsert {
	u.SetExcluded(llmtokenusage.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(llmtokenusage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LlmTokenUsageUpsertOne) UpdateNewValues() *LlmTokenUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(llmtokenusage.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LlmTokenUsageUpsertOne) Ignore() *LlmTokenUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LlmTokenUsageUpsertOne) DoNothing() *LlmTokenUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LlmTokenUsageCreate.OnConflict
// documentation for more info.
func (u *LlmTokenUsageUpsertOne) Update(set func(*LlmTokenUsageUpsert)) *LlmTokenUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LlmTokenUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *LlmTokenUsageUpsertOne) SetModelID(v uuid.UUID) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateModelID() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateModelID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LlmTokenUsageUpsertOne) SetUserID(v uuid.UUID) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateUserID() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LlmTokenUsageUpsertOne) ClearUserID() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.ClearUserID()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *LlmTokenUsageUpsertOne) SetPromptTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *LlmTokenUsageUpsertOne) AddPromptTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdatePromptTokens() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *LlmTokenUsageUpsertOne) SetCompletionTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *LlmTokenUsageUpsertOne) AddCompletionTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateCompletionTokens() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *LlmTokenUsageUpsertOne) SetTotalTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *LlmTokenUsageUpsertOne) AddTotalTokens(v int) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateTotalTokens() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCostAmount sets the "cost_amount" field.
func (u *LlmTokenUsageUpsertOne) SetCostAmount(v float64) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCostAmount(v)
	})
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *LlmTokenUsageUpsertOne) AddCostAmount(v float64) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddCostAmount(v)
	})
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateCostAmount() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCostAmount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LlmTokenUsageUpsertOne) SetCreatedAt(v time.Time) *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertOne) UpdateCreatedAt() *LlmTokenUsageUpsertOne {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *LlmTokenUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LlmTokenUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LlmTokenUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LlmTokenUsageUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LlmTokenUsageUpsertOne.ID is not supported by MySQL driver. Use LlmTokenUsageUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LlmTokenUsageUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LlmTokenUsageCreateBulk is the builder for creating many LlmTokenUsage entities in bulk.
type LlmTokenUsageCreateBulk struct {
	config
	err      error
	builders []*LlmTokenUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the LlmTokenUsage entities in the database.
func (_c *LlmTokenUsageCreateBulk) Save(ctx context.Context) ([]*LlmTokenUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LlmTokenUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LlmTokenUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LlmTokenUsageCreateBulk) SaveX(ctx context.Context) []*LlmTokenUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LlmTokenUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LlmTokenUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LlmTokenUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LlmTokenUsageUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *LlmTokenUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *LlmTokenUsageUpsertBulk {
	_c.conflict = opts
	return &LlmTokenUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LlmTokenUsageCreateBulk) OnConflictColumns(columns ...string) *LlmTokenUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LlmTokenUsageUpsertBulk{
		create: _c,
	}
}

// LlmTokenUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of LlmTokenUsage nodes.
type LlmTokenUsageUpsertBulk struct {
	create *LlmTokenUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(llmtokenusage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LlmTokenUsageUpsertBulk) UpdateNewValues() *LlmTokenUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(llmtokenusage.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LlmTokenUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LlmTokenUsageUpsertBulk) Ignore() *LlmTokenUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LlmTokenUsageUpsertBulk) DoNothing() *LlmTokenUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LlmTokenUsageCreateBulk.OnConflict
// documentation for more info.
func (u *LlmTokenUsageUpsertBulk) Update(set func(*LlmTokenUsageUpsert)) *LlmTokenUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LlmTokenUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *LlmTokenUsageUpsertBulk) SetModelID(v uuid.UUID) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateModelID() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateModelID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LlmTokenUsageUpsertBulk) SetUserID(v uuid.UUID) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateUserID() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LlmTokenUsageUpsertBulk) ClearUserID() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.ClearUserID()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *LlmTokenUsageUpsertBulk) SetPromptTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *LlmTokenUsageUpsertBulk) AddPromptTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdatePromptTokens() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *LlmTokenUsageUpsertBulk) SetCompletionTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *LlmTokenUsageUpsertBulk) AddCompletionTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateCompletionTokens() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *LlmTokenUsageUpsertBulk) SetTotalTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *LlmTokenUsageUpsertBulk) AddTotalTokens(v int) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateTotalTokens() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCostAmount sets the "cost_amount" field.
func (u *LlmTokenUsageUpsertBulk) SetCostAmount(v float64) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCostAmount(v)
	})
}

// AddCostAmount adds v to the "cost_amount" field.
func (u *LlmTokenUsageUpsertBulk) AddCostAmount(v float64) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.AddCostAmount(v)
	})
}

// UpdateCostAmount sets the "cost_amount" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateCostAmount() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCostAmount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *LlmTokenUsageUpsertBulk) SetCreatedAt(v time.Time) *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LlmTokenUsageUpsertBulk) UpdateCreatedAt() *LlmTokenUsageUpsertBulk {
	return u.Update(func(s *LlmTokenUsageUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *LlmTokenUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LlmTokenUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LlmTokenUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LlmTokenUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
