// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moon/ent/predicate"
	"moon/ent/procurementexpert"
	"moon/ent/procurementimplementation"
	"moon/ent/procurementreview"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// ProcurementReviewUpdate is the builder for updating ProcurementReview entities.
type ProcurementReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ProcurementReviewMutation
}

// Where appends a list predicates to the ProcurementReviewUpdate builder.
func (_u *ProcurementReviewUpdate) Where(ps ...predicate.ProcurementReview) *ProcurementReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProcurementReviewName sets the "ProcurementReviewName" field.
func (_u *ProcurementReviewUpdate) SetProcurementReviewName(v string) *ProcurementReviewUpdate {
	_u.mutation.SetProcurementReviewName(v)
	return _u
}

// SetNillableProcurementReviewName sets the "ProcurementReviewName" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableProcurementReviewName(v *string) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetProcurementReviewName(*v)
	}
	return _u
}

// SetProcurementReviewCode sets the "ProcurementReviewCode" field.
func (_u *ProcurementReviewUpdate) SetProcurementReviewCode(v string) *ProcurementReviewUpdate {
	_u.mutation.SetProcurementReviewCode(v)
	return _u
}

// SetNillableProcurementReviewCode sets the "ProcurementReviewCode" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableProcurementReviewCode(v *string) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetProcurementReviewCode(*v)
	}
	return _u
}

// SetProcurementReviewResult sets the "ProcurementReviewResult" field.
func (_u *ProcurementReviewUpdate) SetProcurementReviewResult(v string) *ProcurementReviewUpdate {
	_u.mutation.SetProcurementReviewResult(v)
	return _u
}

// SetNillableProcurementReviewResult sets the "ProcurementReviewResult" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableProcurementReviewResult(v *string) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetProcurementReviewResult(*v)
	}
	return _u
}

// SetProcurementReviewOpinion sets the "ProcurementReviewOpinion" field.
func (_u *ProcurementReviewUpdate) SetProcurementReviewOpinion(v string) *ProcurementReviewUpdate {
	_u.mutation.SetProcurementReviewOpinion(v)
	return _u
}

// SetNillableProcurementReviewOpinion sets the "ProcurementReviewOpinion" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableProcurementReviewOpinion(v *string) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetProcurementReviewOpinion(*v)
	}
	return _u
}

// SetOtherMetadata sets the "OtherMetadata" field.
func (_u *ProcurementReviewUpdate) SetOtherMetadata(v map[string]interface{}) *ProcurementReviewUpdate {
	_u.mutation.SetOtherMetadata(v)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *ProcurementReviewUpdate) SetCreatedAt(v time.Time) *ProcurementReviewUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableCreatedAt(v *time.Time) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *ProcurementReviewUpdate) SetUpdatedAt(v time.Time) *ProcurementReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableUpdatedAt(v *time.Time) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "UpdatedAt" field.
func (_u *ProcurementReviewUpdate) ClearUpdatedAt() *ProcurementReviewUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProcurementImplementationID sets the "procurement_implementation_id" field.
func (_u *ProcurementReviewUpdate) SetProcurementImplementationID(v uuid.UUID) *ProcurementReviewUpdate {
	_u.mutation.SetProcurementImplementationID(v)
	return _u
}

// SetNillableProcurementImplementationID sets the "procurement_implementation_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableProcurementImplementationID(v *uuid.UUID) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetProcurementImplementationID(*v)
	}
	return _u
}

// ClearProcurementImplementationID clears the value of the "procurement_implementation_id" field.
func (_u *ProcurementReviewUpdate) ClearProcurementImplementationID() *ProcurementReviewUpdate {
	_u.mutation.ClearProcurementImplementationID()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ProcurementReviewUpdate) SetOrganizationID(v uuid.UUID) *ProcurementReviewUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableOrganizationID(v *uuid.UUID) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *ProcurementReviewUpdate) ClearOrganizationID() *ProcurementReviewUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProcurementReviewUpdate) SetUserID(v uuid.UUID) *ProcurementReviewUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdate) SetNillableUserID(v *uuid.UUID) *ProcurementReviewUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ProcurementReviewUpdate) ClearUserID() *ProcurementReviewUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetProcurementImplementation sets the "procurement_implementation" edge to the ProcurementImplementation entity.
func (_u *ProcurementReviewUpdate) SetProcurementImplementation(v *ProcurementImplementation) *ProcurementReviewUpdate {
	return _u.SetProcurementImplementationID(v.ID)
}

// AddProcurementExpertIDs adds the "procurement_experts" edge to the ProcurementExpert entity by IDs.
func (_u *ProcurementReviewUpdate) AddProcurementExpertIDs(ids ...uuid.UUID) *ProcurementReviewUpdate {
	_u.mutation.AddProcurementExpertIDs(ids...)
	return _u
}

// AddProcurementExperts adds the "procurement_experts" edges to the ProcurementExpert entity.
func (_u *ProcurementReviewUpdate) AddProcurementExperts(v ...*ProcurementExpert) *ProcurementReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProcurementExpertIDs(ids...)
}

// Mutation returns the ProcurementReviewMutation object of the builder.
func (_u *ProcurementReviewUpdate) Mutation() *ProcurementReviewMutation {
	return _u.mutation
}

// ClearProcurementImplementation clears the "procurement_implementation" edge to the ProcurementImplementation entity.
func (_u *ProcurementReviewUpdate) ClearProcurementImplementation() *ProcurementReviewUpdate {
	_u.mutation.ClearProcurementImplementation()
	return _u
}

// ClearProcurementExperts clears all "procurement_experts" edges to the ProcurementExpert entity.
func (_u *ProcurementReviewUpdate) ClearProcurementExperts() *ProcurementReviewUpdate {
	_u.mutation.ClearProcurementExperts()
	return _u
}

// RemoveProcurementExpertIDs removes the "procurement_experts" edge to ProcurementExpert entities by IDs.
func (_u *ProcurementReviewUpdate) RemoveProcurementExpertIDs(ids ...uuid.UUID) *ProcurementReviewUpdate {
	_u.mutation.RemoveProcurementExpertIDs(ids...)
	return _u
}

// RemoveProcurementExperts removes "procurement_experts" edges to ProcurementExpert entities.
func (_u *ProcurementReviewUpdate) RemoveProcurementExperts(v ...*ProcurementExpert) *ProcurementReviewUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProcurementExpertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcurementReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcurementReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcurementReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcurementReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProcurementReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(procurementreview.Table, procurementreview.Columns, sqlgraph.NewFieldSpec(procurementreview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProcurementReviewName(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewCode(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewResult(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewOpinion(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewOpinion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtherMetadata(); ok {
		_spec.SetField(procurementreview.FieldOtherMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(procurementreview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(procurementreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(procurementreview.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(procurementreview.FieldOrganizationID, field.TypeUUID, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(procurementreview.FieldOrganizationID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(procurementreview.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(procurementreview.FieldUserID, field.TypeUUID)
	}
	if _u.mutation.ProcurementImplementationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   procurementreview.ProcurementImplementationTable,
			Columns: []string{procurementreview.ProcurementImplementationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementimplementation.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReview
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProcurementImplementationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   procurementreview.ProcurementImplementationTable,
			Columns: []string{procurementreview.ProcurementImplementationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementimplementation.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReview
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProcurementExpertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProcurementExpertsIDs(); len(nodes) > 0 && !_u.mutation.ProcurementExpertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProcurementExpertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.ProcurementReview
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{procurementreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcurementReviewUpdateOne is the builder for updating a single ProcurementReview entity.
type ProcurementReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcurementReviewMutation
}

// SetProcurementReviewName sets the "ProcurementReviewName" field.
func (_u *ProcurementReviewUpdateOne) SetProcurementReviewName(v string) *ProcurementReviewUpdateOne {
	_u.mutation.SetProcurementReviewName(v)
	return _u
}

// SetNillableProcurementReviewName sets the "ProcurementReviewName" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableProcurementReviewName(v *string) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetProcurementReviewName(*v)
	}
	return _u
}

// SetProcurementReviewCode sets the "ProcurementReviewCode" field.
func (_u *ProcurementReviewUpdateOne) SetProcurementReviewCode(v string) *ProcurementReviewUpdateOne {
	_u.mutation.SetProcurementReviewCode(v)
	return _u
}

// SetNillableProcurementReviewCode sets the "ProcurementReviewCode" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableProcurementReviewCode(v *string) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetProcurementReviewCode(*v)
	}
	return _u
}

// SetProcurementReviewResult sets the "ProcurementReviewResult" field.
func (_u *ProcurementReviewUpdateOne) SetProcurementReviewResult(v string) *ProcurementReviewUpdateOne {
	_u.mutation.SetProcurementReviewResult(v)
	return _u
}

// SetNillableProcurementReviewResult sets the "ProcurementReviewResult" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableProcurementReviewResult(v *string) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetProcurementReviewResult(*v)
	}
	return _u
}

// SetProcurementReviewOpinion sets the "ProcurementReviewOpinion" field.
func (_u *ProcurementReviewUpdateOne) SetProcurementReviewOpinion(v string) *ProcurementReviewUpdateOne {
	_u.mutation.SetProcurementReviewOpinion(v)
	return _u
}

// SetNillableProcurementReviewOpinion sets the "ProcurementReviewOpinion" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableProcurementReviewOpinion(v *string) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetProcurementReviewOpinion(*v)
	}
	return _u
}

// SetOtherMetadata sets the "OtherMetadata" field.
func (_u *ProcurementReviewUpdateOne) SetOtherMetadata(v map[string]interface{}) *ProcurementReviewUpdateOne {
	_u.mutation.SetOtherMetadata(v)
	return _u
}

// SetCreatedAt sets the "CreatedAt" field.
func (_u *ProcurementReviewUpdateOne) SetCreatedAt(v time.Time) *ProcurementReviewUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "CreatedAt" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableCreatedAt(v *time.Time) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "UpdatedAt" field.
func (_u *ProcurementReviewUpdateOne) SetUpdatedAt(v time.Time) *ProcurementReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "UpdatedAt" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableUpdatedAt(v *time.Time) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "UpdatedAt" field.
func (_u *ProcurementReviewUpdateOne) ClearUpdatedAt() *ProcurementReviewUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProcurementImplementationID sets the "procurement_implementation_id" field.
func (_u *ProcurementReviewUpdateOne) SetProcurementImplementationID(v uuid.UUID) *ProcurementReviewUpdateOne {
	_u.mutation.SetProcurementImplementationID(v)
	return _u
}

// SetNillableProcurementImplementationID sets the "procurement_implementation_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableProcurementImplementationID(v *uuid.UUID) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetProcurementImplementationID(*v)
	}
	return _u
}

// ClearProcurementImplementationID clears the value of the "procurement_implementation_id" field.
func (_u *ProcurementReviewUpdateOne) ClearProcurementImplementationID() *ProcurementReviewUpdateOne {
	_u.mutation.ClearProcurementImplementationID()
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ProcurementReviewUpdateOne) SetOrganizationID(v uuid.UUID) *ProcurementReviewUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *ProcurementReviewUpdateOne) ClearOrganizationID() *ProcurementReviewUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProcurementReviewUpdateOne) SetUserID(v uuid.UUID) *ProcurementReviewUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProcurementReviewUpdateOne) SetNillableUserID(v *uuid.UUID) *ProcurementReviewUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ProcurementReviewUpdateOne) ClearUserID() *ProcurementReviewUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetProcurementImplementation sets the "procurement_implementation" edge to the ProcurementImplementation entity.
func (_u *ProcurementReviewUpdateOne) SetProcurementImplementation(v *ProcurementImplementation) *ProcurementReviewUpdateOne {
	return _u.SetProcurementImplementationID(v.ID)
}

// AddProcurementExpertIDs adds the "procurement_experts" edge to the ProcurementExpert entity by IDs.
func (_u *ProcurementReviewUpdateOne) AddProcurementExpertIDs(ids ...uuid.UUID) *ProcurementReviewUpdateOne {
	_u.mutation.AddProcurementExpertIDs(ids...)
	return _u
}

// AddProcurementExperts adds the "procurement_experts" edges to the ProcurementExpert entity.
func (_u *ProcurementReviewUpdateOne) AddProcurementExperts(v ...*ProcurementExpert) *ProcurementReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProcurementExpertIDs(ids...)
}

// Mutation returns the ProcurementReviewMutation object of the builder.
func (_u *ProcurementReviewUpdateOne) Mutation() *ProcurementReviewMutation {
	return _u.mutation
}

// ClearProcurementImplementation clears the "procurement_implementation" edge to the ProcurementImplementation entity.
func (_u *ProcurementReviewUpdateOne) ClearProcurementImplementation() *ProcurementReviewUpdateOne {
	_u.mutation.ClearProcurementImplementation()
	return _u
}

// ClearProcurementExperts clears all "procurement_experts" edges to the ProcurementExpert entity.
func (_u *ProcurementReviewUpdateOne) ClearProcurementExperts() *ProcurementReviewUpdateOne {
	_u.mutation.ClearProcurementExperts()
	return _u
}

// RemoveProcurementExpertIDs removes the "procurement_experts" edge to ProcurementExpert entities by IDs.
func (_u *ProcurementReviewUpdateOne) RemoveProcurementExpertIDs(ids ...uuid.UUID) *ProcurementReviewUpdateOne {
	_u.mutation.RemoveProcurementExpertIDs(ids...)
	return _u
}

// RemoveProcurementExperts removes "procurement_experts" edges to ProcurementExpert entities.
func (_u *ProcurementReviewUpdateOne) RemoveProcurementExperts(v ...*ProcurementExpert) *ProcurementReviewUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProcurementExpertIDs(ids...)
}

// Where appends a list predicates to the ProcurementReviewUpdate builder.
func (_u *ProcurementReviewUpdateOne) Where(ps ...predicate.ProcurementReview) *ProcurementReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcurementReviewUpdateOne) Select(field string, fields ...string) *ProcurementReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProcurementReview entity.
func (_u *ProcurementReviewUpdateOne) Save(ctx context.Context) (*ProcurementReview, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcurementReviewUpdateOne) SaveX(ctx context.Context) *ProcurementReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcurementReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcurementReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProcurementReviewUpdateOne) sqlSave(ctx context.Context) (_node *ProcurementReview, err error) {
	_spec := sqlgraph.NewUpdateSpec(procurementreview.Table, procurementreview.Columns, sqlgraph.NewFieldSpec(procurementreview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcurementReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, procurementreview.FieldID)
		for _, f := range fields {
			if !procurementreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != procurementreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProcurementReviewName(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewCode(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewResult(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcurementReviewOpinion(); ok {
		_spec.SetField(procurementreview.FieldProcurementReviewOpinion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OtherMetadata(); ok {
		_spec.SetField(procurementreview.FieldOtherMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(procurementreview.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(procurementreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(procurementreview.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(procurementreview.FieldOrganizationID, field.TypeUUID, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(procurementreview.FieldOrganizationID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(procurementreview.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(procurementreview.FieldUserID, field.TypeUUID)
	}
	if _u.mutation.ProcurementImplementationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   procurementreview.ProcurementImplementationTable,
			Columns: []string{procurementreview.ProcurementImplementationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementimplementation.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReview
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProcurementImplementationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   procurementreview.ProcurementImplementationTable,
			Columns: []string{procurementreview.ProcurementImplementationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementimplementation.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReview
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProcurementExpertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProcurementExpertsIDs(); len(nodes) > 0 && !_u.mutation.ProcurementExpertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProcurementExpertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   procurementreview.ProcurementExpertsTable,
			Columns: procurementreview.ProcurementExpertsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(procurementexpert.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.ProcurementReviewProcurementExperts
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.ProcurementReview
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &ProcurementReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{procurementreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
