// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"moon/ent/procurementimplementation"
	"moon/ent/procurementreview"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProcurementReview is the model entity for the ProcurementReview schema.
type ProcurementReview struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProcurementReviewName holds the value of the "ProcurementReviewName" field.
	ProcurementReviewName string `json:"ProcurementReviewName,omitempty"`
	// ProcurementReviewCode holds the value of the "ProcurementReviewCode" field.
	ProcurementReviewCode string `json:"ProcurementReviewCode,omitempty"`
	// ProcurementReviewResult holds the value of the "ProcurementReviewResult" field.
	ProcurementReviewResult string `json:"ProcurementReviewResult,omitempty"`
	// ProcurementReviewOpinion holds the value of the "ProcurementReviewOpinion" field.
	ProcurementReviewOpinion string `json:"ProcurementReviewOpinion,omitempty"`
	// OtherMetadata holds the value of the "OtherMetadata" field.
	OtherMetadata map[string]interface{} `json:"OtherMetadata,omitempty"`
	// CreatedAt holds the value of the "CreatedAt" field.
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
	// ProcurementImplementationID holds the value of the "procurement_implementation_id" field.
	ProcurementImplementationID *uuid.UUID `json:"procurement_implementation_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *uuid.UUID `json:"organization_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProcurementReviewQuery when eager-loading is set.
	Edges        ProcurementReviewEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProcurementReviewEdges holds the relations/edges for other nodes in the graph.
type ProcurementReviewEdges struct {
	// ProcurementImplementation holds the value of the procurement_implementation edge.
	ProcurementImplementation *ProcurementImplementation `json:"procurement_implementation,omitempty"`
	// ProcurementExperts holds the value of the procurement_experts edge.
	ProcurementExperts []*ProcurementExpert `json:"procurement_experts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedProcurementExperts map[string][]*ProcurementExpert
}

// ProcurementImplementationOrErr returns the ProcurementImplementation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProcurementReviewEdges) ProcurementImplementationOrErr() (*ProcurementImplementation, error) {
	if e.ProcurementImplementation != nil {
		return e.ProcurementImplementation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: procurementimplementation.Label}
	}
	return nil, &NotLoadedError{edge: "procurement_implementation"}
}

// ProcurementExpertsOrErr returns the ProcurementExperts value or an error if the edge
// was not loaded in eager-loading.
func (e ProcurementReviewEdges) ProcurementExpertsOrErr() ([]*ProcurementExpert, error) {
	if e.loadedTypes[1] {
		return e.ProcurementExperts, nil
	}
	return nil, &NotLoadedError{edge: "procurement_experts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProcurementReview) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case procurementreview.FieldProcurementImplementationID, procurementreview.FieldOrganizationID, procurementreview.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case procurementreview.FieldOtherMetadata:
			values[i] = new([]byte)
		case procurementreview.FieldProcurementReviewName, procurementreview.FieldProcurementReviewCode, procurementreview.FieldProcurementReviewResult, procurementreview.FieldProcurementReviewOpinion:
			values[i] = new(sql.NullString)
		case procurementreview.FieldCreatedAt, procurementreview.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case procurementreview.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProcurementReview fields.
func (_m *ProcurementReview) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case procurementreview.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case procurementreview.FieldProcurementReviewName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementReviewName", values[i])
			} else if value.Valid {
				_m.ProcurementReviewName = value.String
			}
		case procurementreview.FieldProcurementReviewCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementReviewCode", values[i])
			} else if value.Valid {
				_m.ProcurementReviewCode = value.String
			}
		case procurementreview.FieldProcurementReviewResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementReviewResult", values[i])
			} else if value.Valid {
				_m.ProcurementReviewResult = value.String
			}
		case procurementreview.FieldProcurementReviewOpinion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementReviewOpinion", values[i])
			} else if value.Valid {
				_m.ProcurementReviewOpinion = value.String
			}
		case procurementreview.FieldOtherMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field OtherMetadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OtherMetadata); err != nil {
					return fmt.Errorf("unmarshal field OtherMetadata: %w", err)
				}
			}
		case procurementreview.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CreatedAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case procurementreview.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case procurementreview.FieldProcurementImplementationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field procurement_implementation_id", values[i])
			} else if value.Valid {
				_m.ProcurementImplementationID = new(uuid.UUID)
				*_m.ProcurementImplementationID = *value.S.(*uuid.UUID)
			}
		case procurementreview.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(uuid.UUID)
				*_m.OrganizationID = *value.S.(*uuid.UUID)
			}
		case procurementreview.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProcurementReview.
// This includes values selected through modifiers, order, etc.
func (_m *ProcurementReview) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProcurementImplementation queries the "procurement_implementation" edge of the ProcurementReview entity.
func (_m *ProcurementReview) QueryProcurementImplementation() *ProcurementImplementationQuery {
	return NewProcurementReviewClient(_m.config).QueryProcurementImplementation(_m)
}

// QueryProcurementExperts queries the "procurement_experts" edge of the ProcurementReview entity.
func (_m *ProcurementReview) QueryProcurementExperts() *ProcurementExpertQuery {
	return NewProcurementReviewClient(_m.config).QueryProcurementExperts(_m)
}

// Update returns a builder for updating this ProcurementReview.
// Note that you need to call ProcurementReview.Unwrap() before calling this method if this ProcurementReview
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProcurementReview) Update() *ProcurementReviewUpdateOne {
	return NewProcurementReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProcurementReview entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProcurementReview) Unwrap() *ProcurementReview {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProcurementReview is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProcurementReview) String() string {
	var builder strings.Builder
	builder.WriteString("ProcurementReview(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ProcurementReviewName=")
	builder.WriteString(_m.ProcurementReviewName)
	builder.WriteString(", ")
	builder.WriteString("ProcurementReviewCode=")
	builder.WriteString(_m.ProcurementReviewCode)
	builder.WriteString(", ")
	builder.WriteString("ProcurementReviewResult=")
	builder.WriteString(_m.ProcurementReviewResult)
	builder.WriteString(", ")
	builder.WriteString("ProcurementReviewOpinion=")
	builder.WriteString(_m.ProcurementReviewOpinion)
	builder.WriteString(", ")
	builder.WriteString("OtherMetadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.OtherMetadata))
	builder.WriteString(", ")
	builder.WriteString("CreatedAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("UpdatedAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ProcurementImplementationID; v != nil {
		builder.WriteString("procurement_implementation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedProcurementExperts returns the ProcurementExperts named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *ProcurementReview) NamedProcurementExperts(name string) ([]*ProcurementExpert, error) {
	if _m.Edges.namedProcurementExperts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProcurementExperts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *ProcurementReview) appendNamedProcurementExperts(name string, edges ...*ProcurementExpert) {
	if _m.Edges.namedProcurementExperts == nil {
		_m.Edges.namedProcurementExperts = make(map[string][]*ProcurementExpert)
	}
	if len(edges) == 0 {
		_m.Edges.namedProcurementExperts[name] = []*ProcurementExpert{}
	} else {
		_m.Edges.namedProcurementExperts[name] = append(_m.Edges.namedProcurementExperts[name], edges...)
	}
}

// ProcurementReviews is a parsable slice of ProcurementReview.
type ProcurementReviews []*ProcurementReview
