// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"moon/ent/procurementexpert"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProcurementExpert is the model entity for the ProcurementExpert schema.
type ProcurementExpert struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProcurementExpertName holds the value of the "ProcurementExpertName" field.
	ProcurementExpertName string `json:"ProcurementExpertName,omitempty"`
	// ProcurementExpertCode holds the value of the "ProcurementExpertCode" field.
	ProcurementExpertCode string `json:"ProcurementExpertCode,omitempty"`
	// ProcurementExpertDescription holds the value of the "ProcurementExpertDescription" field.
	ProcurementExpertDescription string `json:"ProcurementExpertDescription,omitempty"`
	// ProcurementExpertFlag holds the value of the "ProcurementExpertFlag" field.
	ProcurementExpertFlag string `json:"ProcurementExpertFlag,omitempty"`
	// ProcurementExpertJobGrade holds the value of the "ProcurementExpertJobGrade" field.
	ProcurementExpertJobGrade string `json:"ProcurementExpertJobGrade,omitempty"`
	// ProcurementExpertBankName holds the value of the "ProcurementExpertBankName" field.
	ProcurementExpertBankName string `json:"ProcurementExpertBankName,omitempty"`
	// ProcurementExpertBankAccount holds the value of the "ProcurementExpertBankAccount" field.
	ProcurementExpertBankAccount string `json:"ProcurementExpertBankAccount,omitempty"`
	// OtherMetadata holds the value of the "OtherMetadata" field.
	OtherMetadata map[string]interface{} `json:"OtherMetadata,omitempty"`
	// CreatedAt holds the value of the "CreatedAt" field.
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *uuid.UUID `json:"organization_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProcurementExpertQuery when eager-loading is set.
	Edges        ProcurementExpertEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProcurementExpertEdges holds the relations/edges for other nodes in the graph.
type ProcurementExpertEdges struct {
	// ProcurementReviews holds the value of the procurement_reviews edge.
	ProcurementReviews []*ProcurementReview `json:"procurement_reviews,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedProcurementReviews map[string][]*ProcurementReview
}

// ProcurementReviewsOrErr returns the ProcurementReviews value or an error if the edge
// was not loaded in eager-loading.
func (e ProcurementExpertEdges) ProcurementReviewsOrErr() ([]*ProcurementReview, error) {
	if e.loadedTypes[0] {
		return e.ProcurementReviews, nil
	}
	return nil, &NotLoadedError{edge: "procurement_reviews"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProcurementExpert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case procurementexpert.FieldOrganizationID, procurementexpert.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case procurementexpert.FieldOtherMetadata:
			values[i] = new([]byte)
		case procurementexpert.FieldProcurementExpertName, procurementexpert.FieldProcurementExpertCode, procurementexpert.FieldProcurementExpertDescription, procurementexpert.FieldProcurementExpertFlag, procurementexpert.FieldProcurementExpertJobGrade, procurementexpert.FieldProcurementExpertBankName, procurementexpert.FieldProcurementExpertBankAccount:
			values[i] = new(sql.NullString)
		case procurementexpert.FieldCreatedAt, procurementexpert.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case procurementexpert.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProcurementExpert fields.
func (_m *ProcurementExpert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case procurementexpert.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case procurementexpert.FieldProcurementExpertName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertName", values[i])
			} else if value.Valid {
				_m.ProcurementExpertName = value.String
			}
		case procurementexpert.FieldProcurementExpertCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertCode", values[i])
			} else if value.Valid {
				_m.ProcurementExpertCode = value.String
			}
		case procurementexpert.FieldProcurementExpertDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertDescription", values[i])
			} else if value.Valid {
				_m.ProcurementExpertDescription = value.String
			}
		case procurementexpert.FieldProcurementExpertFlag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertFlag", values[i])
			} else if value.Valid {
				_m.ProcurementExpertFlag = value.String
			}
		case procurementexpert.FieldProcurementExpertJobGrade:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertJobGrade", values[i])
			} else if value.Valid {
				_m.ProcurementExpertJobGrade = value.String
			}
		case procurementexpert.FieldProcurementExpertBankName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertBankName", values[i])
			} else if value.Valid {
				_m.ProcurementExpertBankName = value.String
			}
		case procurementexpert.FieldProcurementExpertBankAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ProcurementExpertBankAccount", values[i])
			} else if value.Valid {
				_m.ProcurementExpertBankAccount = value.String
			}
		case procurementexpert.FieldOtherMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field OtherMetadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OtherMetadata); err != nil {
					return fmt.Errorf("unmarshal field OtherMetadata: %w", err)
				}
			}
		case procurementexpert.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CreatedAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case procurementexpert.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case procurementexpert.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(uuid.UUID)
				*_m.OrganizationID = *value.S.(*uuid.UUID)
			}
		case procurementexpert.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProcurementExpert.
// This includes values selected through modifiers, order, etc.
func (_m *ProcurementExpert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProcurementReviews queries the "procurement_reviews" edge of the ProcurementExpert entity.
func (_m *ProcurementExpert) QueryProcurementReviews() *ProcurementReviewQuery {
	return NewProcurementExpertClient(_m.config).QueryProcurementReviews(_m)
}

// Update returns a builder for updating this ProcurementExpert.
// Note that you need to call ProcurementExpert.Unwrap() before calling this method if this ProcurementExpert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProcurementExpert) Update() *ProcurementExpertUpdateOne {
	return NewProcurementExpertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProcurementExpert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProcurementExpert) Unwrap() *ProcurementExpert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProcurementExpert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProcurementExpert) String() string {
	var builder strings.Builder
	builder.WriteString("ProcurementExpert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ProcurementExpertName=")
	builder.WriteString(_m.ProcurementExpertName)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertCode=")
	builder.WriteString(_m.ProcurementExpertCode)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertDescription=")
	builder.WriteString(_m.ProcurementExpertDescription)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertFlag=")
	builder.WriteString(_m.ProcurementExpertFlag)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertJobGrade=")
	builder.WriteString(_m.ProcurementExpertJobGrade)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertBankName=")
	builder.WriteString(_m.ProcurementExpertBankName)
	builder.WriteString(", ")
	builder.WriteString("ProcurementExpertBankAccount=")
	builder.WriteString(_m.ProcurementExpertBankAccount)
	builder.WriteString(", ")
	builder.WriteString("OtherMetadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.OtherMetadata))
	builder.WriteString(", ")
	builder.WriteString("CreatedAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("UpdatedAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedProcurementReviews returns the ProcurementReviews named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *ProcurementExpert) NamedProcurementReviews(name string) ([]*ProcurementReview, error) {
	if _m.Edges.namedProcurementReviews == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProcurementReviews[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *ProcurementExpert) appendNamedProcurementReviews(name string, edges ...*ProcurementReview) {
	if _m.Edges.namedProcurementReviews == nil {
		_m.Edges.namedProcurementReviews = make(map[string][]*ProcurementReview)
	}
	if len(edges) == 0 {
		_m.Edges.namedProcurementReviews[name] = []*ProcurementReview{}
	} else {
		_m.Edges.namedProcurementReviews[name] = append(_m.Edges.namedProcurementReviews[name], edges...)
	}
}

// ProcurementExperts is a parsable slice of ProcurementExpert.
type ProcurementExperts []*ProcurementExpert
