// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"moon/ent/predicate"
	"moon/ent/procurementacceptance"
	"moon/ent/procurementimplementation"
	"moon/ent/procurementplan"
	"moon/ent/procurementreview"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// ProcurementImplementationQuery is the builder for querying ProcurementImplementation entities.
type ProcurementImplementationQuery struct {
	config
	ctx                       *QueryContext
	order                     []procurementimplementation.OrderOption
	inters                    []Interceptor
	predicates                []predicate.ProcurementImplementation
	withProcurementPlan       *ProcurementPlanQuery
	withProcurementAcceptance *ProcurementAcceptanceQuery
	withProcurementReview     *ProcurementReviewQuery
	modifiers                 []func(*sql.Selector)
	loadTotal                 []func(context.Context, []*ProcurementImplementation) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProcurementImplementationQuery builder.
func (_q *ProcurementImplementationQuery) Where(ps ...predicate.ProcurementImplementation) *ProcurementImplementationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProcurementImplementationQuery) Limit(limit int) *ProcurementImplementationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProcurementImplementationQuery) Offset(offset int) *ProcurementImplementationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProcurementImplementationQuery) Unique(unique bool) *ProcurementImplementationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProcurementImplementationQuery) Order(o ...procurementimplementation.OrderOption) *ProcurementImplementationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProcurementPlan chains the current query on the "procurement_plan" edge.
func (_q *ProcurementImplementationQuery) QueryProcurementPlan() *ProcurementPlanQuery {
	query := (&ProcurementPlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(procurementimplementation.Table, procurementimplementation.FieldID, selector),
			sqlgraph.To(procurementplan.Table, procurementplan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, procurementimplementation.ProcurementPlanTable, procurementimplementation.ProcurementPlanColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.ProcurementPlan
		step.Edge.Schema = schemaConfig.ProcurementImplementation
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProcurementAcceptance chains the current query on the "procurement_acceptance" edge.
func (_q *ProcurementImplementationQuery) QueryProcurementAcceptance() *ProcurementAcceptanceQuery {
	query := (&ProcurementAcceptanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(procurementimplementation.Table, procurementimplementation.FieldID, selector),
			sqlgraph.To(procurementacceptance.Table, procurementacceptance.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, procurementimplementation.ProcurementAcceptanceTable, procurementimplementation.ProcurementAcceptanceColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.ProcurementAcceptance
		step.Edge.Schema = schemaConfig.ProcurementAcceptance
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProcurementReview chains the current query on the "procurement_review" edge.
func (_q *ProcurementImplementationQuery) QueryProcurementReview() *ProcurementReviewQuery {
	query := (&ProcurementReviewClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(procurementimplementation.Table, procurementimplementation.FieldID, selector),
			sqlgraph.To(procurementreview.Table, procurementreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, procurementimplementation.ProcurementReviewTable, procurementimplementation.ProcurementReviewColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.ProcurementReview
		step.Edge.Schema = schemaConfig.ProcurementReview
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProcurementImplementation entity from the query.
// Returns a *NotFoundError when no ProcurementImplementation was found.
func (_q *ProcurementImplementationQuery) First(ctx context.Context) (*ProcurementImplementation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{procurementimplementation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) FirstX(ctx context.Context) *ProcurementImplementation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProcurementImplementation ID from the query.
// Returns a *NotFoundError when no ProcurementImplementation ID was found.
func (_q *ProcurementImplementationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{procurementimplementation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProcurementImplementation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProcurementImplementation entity is found.
// Returns a *NotFoundError when no ProcurementImplementation entities are found.
func (_q *ProcurementImplementationQuery) Only(ctx context.Context) (*ProcurementImplementation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{procurementimplementation.Label}
	default:
		return nil, &NotSingularError{procurementimplementation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) OnlyX(ctx context.Context) *ProcurementImplementation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProcurementImplementation ID in the query.
// Returns a *NotSingularError when more than one ProcurementImplementation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProcurementImplementationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{procurementimplementation.Label}
	default:
		err = &NotSingularError{procurementimplementation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProcurementImplementations.
func (_q *ProcurementImplementationQuery) All(ctx context.Context) ([]*ProcurementImplementation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProcurementImplementation, *ProcurementImplementationQuery]()
	return withInterceptors[[]*ProcurementImplementation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) AllX(ctx context.Context) []*ProcurementImplementation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProcurementImplementation IDs.
func (_q *ProcurementImplementationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(procurementimplementation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProcurementImplementationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProcurementImplementationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProcurementImplementationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProcurementImplementationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProcurementImplementationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProcurementImplementationQuery) Clone() *ProcurementImplementationQuery {
	if _q == nil {
		return nil
	}
	return &ProcurementImplementationQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]procurementimplementation.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.ProcurementImplementation{}, _q.predicates...),
		withProcurementPlan:       _q.withProcurementPlan.Clone(),
		withProcurementAcceptance: _q.withProcurementAcceptance.Clone(),
		withProcurementReview:     _q.withProcurementReview.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProcurementPlan tells the query-builder to eager-load the nodes that are connected to
// the "procurement_plan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProcurementImplementationQuery) WithProcurementPlan(opts ...func(*ProcurementPlanQuery)) *ProcurementImplementationQuery {
	query := (&ProcurementPlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProcurementPlan = query
	return _q
}

// WithProcurementAcceptance tells the query-builder to eager-load the nodes that are connected to
// the "procurement_acceptance" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProcurementImplementationQuery) WithProcurementAcceptance(opts ...func(*ProcurementAcceptanceQuery)) *ProcurementImplementationQuery {
	query := (&ProcurementAcceptanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProcurementAcceptance = query
	return _q
}

// WithProcurementReview tells the query-builder to eager-load the nodes that are connected to
// the "procurement_review" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProcurementImplementationQuery) WithProcurementReview(opts ...func(*ProcurementReviewQuery)) *ProcurementImplementationQuery {
	query := (&ProcurementReviewClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProcurementReview = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProcurementImplementationName string `json:"ProcurementImplementationName,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProcurementImplementation.Query().
//		GroupBy(procurementimplementation.FieldProcurementImplementationName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProcurementImplementationQuery) GroupBy(field string, fields ...string) *ProcurementImplementationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProcurementImplementationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = procurementimplementation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProcurementImplementationName string `json:"ProcurementImplementationName,omitempty"`
//	}
//
//	client.ProcurementImplementation.Query().
//		Select(procurementimplementation.FieldProcurementImplementationName).
//		Scan(ctx, &v)
func (_q *ProcurementImplementationQuery) Select(fields ...string) *ProcurementImplementationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProcurementImplementationSelect{ProcurementImplementationQuery: _q}
	sbuild.label = procurementimplementation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProcurementImplementationSelect configured with the given aggregations.
func (_q *ProcurementImplementationQuery) Aggregate(fns ...AggregateFunc) *ProcurementImplementationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProcurementImplementationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !procurementimplementation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProcurementImplementationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProcurementImplementation, error) {
	var (
		nodes       = []*ProcurementImplementation{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProcurementPlan != nil,
			_q.withProcurementAcceptance != nil,
			_q.withProcurementReview != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProcurementImplementation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProcurementImplementation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.ProcurementImplementation
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProcurementPlan; query != nil {
		if err := _q.loadProcurementPlan(ctx, query, nodes, nil,
			func(n *ProcurementImplementation, e *ProcurementPlan) { n.Edges.ProcurementPlan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProcurementAcceptance; query != nil {
		if err := _q.loadProcurementAcceptance(ctx, query, nodes, nil,
			func(n *ProcurementImplementation, e *ProcurementAcceptance) { n.Edges.ProcurementAcceptance = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProcurementReview; query != nil {
		if err := _q.loadProcurementReview(ctx, query, nodes, nil,
			func(n *ProcurementImplementation, e *ProcurementReview) { n.Edges.ProcurementReview = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProcurementImplementationQuery) loadProcurementPlan(ctx context.Context, query *ProcurementPlanQuery, nodes []*ProcurementImplementation, init func(*ProcurementImplementation), assign func(*ProcurementImplementation, *ProcurementPlan)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProcurementImplementation)
	for i := range nodes {
		if nodes[i].ProcurementPlanID == nil {
			continue
		}
		fk := *nodes[i].ProcurementPlanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(procurementplan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "procurement_plan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProcurementImplementationQuery) loadProcurementAcceptance(ctx context.Context, query *ProcurementAcceptanceQuery, nodes []*ProcurementImplementation, init func(*ProcurementImplementation), assign func(*ProcurementImplementation, *ProcurementAcceptance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ProcurementImplementation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(procurementacceptance.FieldProcurementImplementationID)
	}
	query.Where(predicate.ProcurementAcceptance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(procurementimplementation.ProcurementAcceptanceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProcurementImplementationID
		if fk == nil {
			return fmt.Errorf(`foreign-key "procurement_implementation_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "procurement_implementation_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ProcurementImplementationQuery) loadProcurementReview(ctx context.Context, query *ProcurementReviewQuery, nodes []*ProcurementImplementation, init func(*ProcurementImplementation), assign func(*ProcurementImplementation, *ProcurementReview)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ProcurementImplementation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(procurementreview.FieldProcurementImplementationID)
	}
	query.Where(predicate.ProcurementReview(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(procurementimplementation.ProcurementReviewColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProcurementImplementationID
		if fk == nil {
			return fmt.Errorf(`foreign-key "procurement_implementation_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "procurement_implementation_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ProcurementImplementationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.ProcurementImplementation
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProcurementImplementationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(procurementimplementation.Table, procurementimplementation.Columns, sqlgraph.NewFieldSpec(procurementimplementation.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, procurementimplementation.FieldID)
		for i := range fields {
			if fields[i] != procurementimplementation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProcurementPlan != nil {
			_spec.Node.AddColumnOnce(procurementimplementation.FieldProcurementPlanID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProcurementImplementationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(procurementimplementation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = procurementimplementation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.ProcurementImplementation)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProcurementImplementationGroupBy is the group-by builder for ProcurementImplementation entities.
type ProcurementImplementationGroupBy struct {
	selector
	build *ProcurementImplementationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProcurementImplementationGroupBy) Aggregate(fns ...AggregateFunc) *ProcurementImplementationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProcurementImplementationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcurementImplementationQuery, *ProcurementImplementationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProcurementImplementationGroupBy) sqlScan(ctx context.Context, root *ProcurementImplementationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProcurementImplementationSelect is the builder for selecting fields of ProcurementImplementation entities.
type ProcurementImplementationSelect struct {
	*ProcurementImplementationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProcurementImplementationSelect) Aggregate(fns ...AggregateFunc) *ProcurementImplementationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProcurementImplementationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProcurementImplementationQuery, *ProcurementImplementationSelect](ctx, _s.ProcurementImplementationQuery, _s, _s.inters, v)
}

func (_s *ProcurementImplementationSelect) sqlScan(ctx context.Context, root *ProcurementImplementationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
