// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"moon/ent/role"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Role is the model entity for the Role schema.
type Role struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RoleName holds the value of the "role_name" field.
	RoleName string `json:"role_name,omitempty"`
	// RoleCode holds the value of the "role_code" field.
	RoleCode string `json:"role_code,omitempty"`
	// RoleDescription holds the value of the "role_description" field.
	RoleDescription string `json:"role_description,omitempty"`
	// RoleFlag holds the value of the "role_flag" field.
	RoleFlag string `json:"role_flag,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoleQuery when eager-loading is set.
	Edges        RoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoleEdges holds the relations/edges for other nodes in the graph.
type RoleEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Permission holds the value of the permission edge.
	Permission []*Permission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedUser       map[string][]*User
	namedPermission map[string][]*Permission
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e RoleEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading.
func (e RoleEdges) PermissionOrErr() ([]*Permission, error) {
	if e.loadedTypes[1] {
		return e.Permission, nil
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Role) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case role.FieldRoleName, role.FieldRoleCode, role.FieldRoleDescription, role.FieldRoleFlag:
			values[i] = new(sql.NullString)
		case role.FieldCreatedAt, role.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case role.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Role fields.
func (_m *Role) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case role.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case role.FieldRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_name", values[i])
			} else if value.Valid {
				_m.RoleName = value.String
			}
		case role.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case role.FieldRoleDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_description", values[i])
			} else if value.Valid {
				_m.RoleDescription = value.String
			}
		case role.FieldRoleFlag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_flag", values[i])
			} else if value.Valid {
				_m.RoleFlag = value.String
			}
		case role.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case role.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Role.
// This includes values selected through modifiers, order, etc.
func (_m *Role) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Role entity.
func (_m *Role) QueryUser() *UserQuery {
	return NewRoleClient(_m.config).QueryUser(_m)
}

// QueryPermission queries the "permission" edge of the Role entity.
func (_m *Role) QueryPermission() *PermissionQuery {
	return NewRoleClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this Role.
// Note that you need to call Role.Unwrap() before calling this method if this Role
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Role) Update() *RoleUpdateOne {
	return NewRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Role entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Role) Unwrap() *Role {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Role is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Role) String() string {
	var builder strings.Builder
	builder.WriteString("Role(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_name=")
	builder.WriteString(_m.RoleName)
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("role_description=")
	builder.WriteString(_m.RoleDescription)
	builder.WriteString(", ")
	builder.WriteString("role_flag=")
	builder.WriteString(_m.RoleFlag)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedUser returns the User named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Role) NamedUser(name string) ([]*User, error) {
	if _m.Edges.namedUser == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUser[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Role) appendNamedUser(name string, edges ...*User) {
	if _m.Edges.namedUser == nil {
		_m.Edges.namedUser = make(map[string][]*User)
	}
	if len(edges) == 0 {
		_m.Edges.namedUser[name] = []*User{}
	} else {
		_m.Edges.namedUser[name] = append(_m.Edges.namedUser[name], edges...)
	}
}

// NamedPermission returns the Permission named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Role) NamedPermission(name string) ([]*Permission, error) {
	if _m.Edges.namedPermission == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPermission[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Role) appendNamedPermission(name string, edges ...*Permission) {
	if _m.Edges.namedPermission == nil {
		_m.Edges.namedPermission = make(map[string][]*Permission)
	}
	if len(edges) == 0 {
		_m.Edges.namedPermission[name] = []*Permission{}
	} else {
		_m.Edges.namedPermission[name] = append(_m.Edges.namedPermission[name], edges...)
	}
}

// Roles is a parsable slice of Role.
type Roles []*Role
