// Code generated by ent, DO NOT EDIT.

package assets

import (
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"

	"moon/ent/internal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldID, id))
}

// AssetName applies equality check predicate on the "asset_name" field. It's identical to AssetNameEQ.
func AssetName(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetName, v))
}

// AssetCode applies equality check predicate on the "asset_code" field. It's identical to AssetCodeEQ.
func AssetCode(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetCode, v))
}

// AssetDescription applies equality check predicate on the "asset_description" field. It's identical to AssetDescriptionEQ.
func AssetDescription(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetDescription, v))
}

// AssetFlag applies equality check predicate on the "asset_flag" field. It's identical to AssetFlagEQ.
func AssetFlag(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetFlag, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldQuantity, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldLocation, v))
}

// PurchasePrice applies equality check predicate on the "purchase_price" field. It's identical to PurchasePriceEQ.
func PurchasePrice(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldPurchasePrice, v))
}

// DepreciationPrice applies equality check predicate on the "depreciation_price" field. It's identical to DepreciationPriceEQ.
func DepreciationPrice(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldDepreciationPrice, v))
}

// PurchaseDate applies equality check predicate on the "purchase_date" field. It's identical to PurchaseDateEQ.
func PurchaseDate(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldPurchaseDate, v))
}

// Manufacturer applies equality check predicate on the "manufacturer" field. It's identical to ManufacturerEQ.
func Manufacturer(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldManufacturer, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldModel, v))
}

// AssetTypeID applies equality check predicate on the "asset_type_id" field. It's identical to AssetTypeIDEQ.
func AssetTypeID(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetTypeID, v))
}

// AssetCategoryID applies equality check predicate on the "asset_category_id" field. It's identical to AssetCategoryIDEQ.
func AssetCategoryID(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetCategoryID, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldOrganizationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldUpdatedAt, v))
}

// AssetNameEQ applies the EQ predicate on the "asset_name" field.
func AssetNameEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetName, v))
}

// AssetNameNEQ applies the NEQ predicate on the "asset_name" field.
func AssetNameNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetName, v))
}

// AssetNameIn applies the In predicate on the "asset_name" field.
func AssetNameIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetName, vs...))
}

// AssetNameNotIn applies the NotIn predicate on the "asset_name" field.
func AssetNameNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetName, vs...))
}

// AssetNameGT applies the GT predicate on the "asset_name" field.
func AssetNameGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldAssetName, v))
}

// AssetNameGTE applies the GTE predicate on the "asset_name" field.
func AssetNameGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldAssetName, v))
}

// AssetNameLT applies the LT predicate on the "asset_name" field.
func AssetNameLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldAssetName, v))
}

// AssetNameLTE applies the LTE predicate on the "asset_name" field.
func AssetNameLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldAssetName, v))
}

// AssetNameContains applies the Contains predicate on the "asset_name" field.
func AssetNameContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldAssetName, v))
}

// AssetNameHasPrefix applies the HasPrefix predicate on the "asset_name" field.
func AssetNameHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldAssetName, v))
}

// AssetNameHasSuffix applies the HasSuffix predicate on the "asset_name" field.
func AssetNameHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldAssetName, v))
}

// AssetNameEqualFold applies the EqualFold predicate on the "asset_name" field.
func AssetNameEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldAssetName, v))
}

// AssetNameContainsFold applies the ContainsFold predicate on the "asset_name" field.
func AssetNameContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldAssetName, v))
}

// AssetCodeEQ applies the EQ predicate on the "asset_code" field.
func AssetCodeEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetCode, v))
}

// AssetCodeNEQ applies the NEQ predicate on the "asset_code" field.
func AssetCodeNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetCode, v))
}

// AssetCodeIn applies the In predicate on the "asset_code" field.
func AssetCodeIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetCode, vs...))
}

// AssetCodeNotIn applies the NotIn predicate on the "asset_code" field.
func AssetCodeNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetCode, vs...))
}

// AssetCodeGT applies the GT predicate on the "asset_code" field.
func AssetCodeGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldAssetCode, v))
}

// AssetCodeGTE applies the GTE predicate on the "asset_code" field.
func AssetCodeGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldAssetCode, v))
}

// AssetCodeLT applies the LT predicate on the "asset_code" field.
func AssetCodeLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldAssetCode, v))
}

// AssetCodeLTE applies the LTE predicate on the "asset_code" field.
func AssetCodeLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldAssetCode, v))
}

// AssetCodeContains applies the Contains predicate on the "asset_code" field.
func AssetCodeContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldAssetCode, v))
}

// AssetCodeHasPrefix applies the HasPrefix predicate on the "asset_code" field.
func AssetCodeHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldAssetCode, v))
}

// AssetCodeHasSuffix applies the HasSuffix predicate on the "asset_code" field.
func AssetCodeHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldAssetCode, v))
}

// AssetCodeEqualFold applies the EqualFold predicate on the "asset_code" field.
func AssetCodeEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldAssetCode, v))
}

// AssetCodeContainsFold applies the ContainsFold predicate on the "asset_code" field.
func AssetCodeContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldAssetCode, v))
}

// AssetDescriptionEQ applies the EQ predicate on the "asset_description" field.
func AssetDescriptionEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetDescription, v))
}

// AssetDescriptionNEQ applies the NEQ predicate on the "asset_description" field.
func AssetDescriptionNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetDescription, v))
}

// AssetDescriptionIn applies the In predicate on the "asset_description" field.
func AssetDescriptionIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetDescription, vs...))
}

// AssetDescriptionNotIn applies the NotIn predicate on the "asset_description" field.
func AssetDescriptionNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetDescription, vs...))
}

// AssetDescriptionGT applies the GT predicate on the "asset_description" field.
func AssetDescriptionGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldAssetDescription, v))
}

// AssetDescriptionGTE applies the GTE predicate on the "asset_description" field.
func AssetDescriptionGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldAssetDescription, v))
}

// AssetDescriptionLT applies the LT predicate on the "asset_description" field.
func AssetDescriptionLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldAssetDescription, v))
}

// AssetDescriptionLTE applies the LTE predicate on the "asset_description" field.
func AssetDescriptionLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldAssetDescription, v))
}

// AssetDescriptionContains applies the Contains predicate on the "asset_description" field.
func AssetDescriptionContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldAssetDescription, v))
}

// AssetDescriptionHasPrefix applies the HasPrefix predicate on the "asset_description" field.
func AssetDescriptionHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldAssetDescription, v))
}

// AssetDescriptionHasSuffix applies the HasSuffix predicate on the "asset_description" field.
func AssetDescriptionHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldAssetDescription, v))
}

// AssetDescriptionEqualFold applies the EqualFold predicate on the "asset_description" field.
func AssetDescriptionEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldAssetDescription, v))
}

// AssetDescriptionContainsFold applies the ContainsFold predicate on the "asset_description" field.
func AssetDescriptionContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldAssetDescription, v))
}

// AssetFlagEQ applies the EQ predicate on the "asset_flag" field.
func AssetFlagEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetFlag, v))
}

// AssetFlagNEQ applies the NEQ predicate on the "asset_flag" field.
func AssetFlagNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetFlag, v))
}

// AssetFlagIn applies the In predicate on the "asset_flag" field.
func AssetFlagIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetFlag, vs...))
}

// AssetFlagNotIn applies the NotIn predicate on the "asset_flag" field.
func AssetFlagNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetFlag, vs...))
}

// AssetFlagGT applies the GT predicate on the "asset_flag" field.
func AssetFlagGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldAssetFlag, v))
}

// AssetFlagGTE applies the GTE predicate on the "asset_flag" field.
func AssetFlagGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldAssetFlag, v))
}

// AssetFlagLT applies the LT predicate on the "asset_flag" field.
func AssetFlagLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldAssetFlag, v))
}

// AssetFlagLTE applies the LTE predicate on the "asset_flag" field.
func AssetFlagLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldAssetFlag, v))
}

// AssetFlagContains applies the Contains predicate on the "asset_flag" field.
func AssetFlagContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldAssetFlag, v))
}

// AssetFlagHasPrefix applies the HasPrefix predicate on the "asset_flag" field.
func AssetFlagHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldAssetFlag, v))
}

// AssetFlagHasSuffix applies the HasSuffix predicate on the "asset_flag" field.
func AssetFlagHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldAssetFlag, v))
}

// AssetFlagEqualFold applies the EqualFold predicate on the "asset_flag" field.
func AssetFlagEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldAssetFlag, v))
}

// AssetFlagContainsFold applies the ContainsFold predicate on the "asset_flag" field.
func AssetFlagContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldAssetFlag, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldQuantity, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldLocation, v))
}

// PurchasePriceEQ applies the EQ predicate on the "purchase_price" field.
func PurchasePriceEQ(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldPurchasePrice, v))
}

// PurchasePriceNEQ applies the NEQ predicate on the "purchase_price" field.
func PurchasePriceNEQ(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldPurchasePrice, v))
}

// PurchasePriceIn applies the In predicate on the "purchase_price" field.
func PurchasePriceIn(vs ...float64) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldPurchasePrice, vs...))
}

// PurchasePriceNotIn applies the NotIn predicate on the "purchase_price" field.
func PurchasePriceNotIn(vs ...float64) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldPurchasePrice, vs...))
}

// PurchasePriceGT applies the GT predicate on the "purchase_price" field.
func PurchasePriceGT(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldPurchasePrice, v))
}

// PurchasePriceGTE applies the GTE predicate on the "purchase_price" field.
func PurchasePriceGTE(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldPurchasePrice, v))
}

// PurchasePriceLT applies the LT predicate on the "purchase_price" field.
func PurchasePriceLT(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldPurchasePrice, v))
}

// PurchasePriceLTE applies the LTE predicate on the "purchase_price" field.
func PurchasePriceLTE(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldPurchasePrice, v))
}

// DepreciationPriceEQ applies the EQ predicate on the "depreciation_price" field.
func DepreciationPriceEQ(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldDepreciationPrice, v))
}

// DepreciationPriceNEQ applies the NEQ predicate on the "depreciation_price" field.
func DepreciationPriceNEQ(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldDepreciationPrice, v))
}

// DepreciationPriceIn applies the In predicate on the "depreciation_price" field.
func DepreciationPriceIn(vs ...float64) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldDepreciationPrice, vs...))
}

// DepreciationPriceNotIn applies the NotIn predicate on the "depreciation_price" field.
func DepreciationPriceNotIn(vs ...float64) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldDepreciationPrice, vs...))
}

// DepreciationPriceGT applies the GT predicate on the "depreciation_price" field.
func DepreciationPriceGT(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldDepreciationPrice, v))
}

// DepreciationPriceGTE applies the GTE predicate on the "depreciation_price" field.
func DepreciationPriceGTE(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldDepreciationPrice, v))
}

// DepreciationPriceLT applies the LT predicate on the "depreciation_price" field.
func DepreciationPriceLT(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldDepreciationPrice, v))
}

// DepreciationPriceLTE applies the LTE predicate on the "depreciation_price" field.
func DepreciationPriceLTE(v float64) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldDepreciationPrice, v))
}

// PurchaseDateEQ applies the EQ predicate on the "purchase_date" field.
func PurchaseDateEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldPurchaseDate, v))
}

// PurchaseDateNEQ applies the NEQ predicate on the "purchase_date" field.
func PurchaseDateNEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldPurchaseDate, v))
}

// PurchaseDateIn applies the In predicate on the "purchase_date" field.
func PurchaseDateIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldPurchaseDate, vs...))
}

// PurchaseDateNotIn applies the NotIn predicate on the "purchase_date" field.
func PurchaseDateNotIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldPurchaseDate, vs...))
}

// PurchaseDateGT applies the GT predicate on the "purchase_date" field.
func PurchaseDateGT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldPurchaseDate, v))
}

// PurchaseDateGTE applies the GTE predicate on the "purchase_date" field.
func PurchaseDateGTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldPurchaseDate, v))
}

// PurchaseDateLT applies the LT predicate on the "purchase_date" field.
func PurchaseDateLT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldPurchaseDate, v))
}

// PurchaseDateLTE applies the LTE predicate on the "purchase_date" field.
func PurchaseDateLTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldPurchaseDate, v))
}

// PurchaseDateIsNil applies the IsNil predicate on the "purchase_date" field.
func PurchaseDateIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldPurchaseDate))
}

// PurchaseDateNotNil applies the NotNil predicate on the "purchase_date" field.
func PurchaseDateNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldPurchaseDate))
}

// ManufacturerEQ applies the EQ predicate on the "manufacturer" field.
func ManufacturerEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldManufacturer, v))
}

// ManufacturerNEQ applies the NEQ predicate on the "manufacturer" field.
func ManufacturerNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldManufacturer, v))
}

// ManufacturerIn applies the In predicate on the "manufacturer" field.
func ManufacturerIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldManufacturer, vs...))
}

// ManufacturerNotIn applies the NotIn predicate on the "manufacturer" field.
func ManufacturerNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldManufacturer, vs...))
}

// ManufacturerGT applies the GT predicate on the "manufacturer" field.
func ManufacturerGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldManufacturer, v))
}

// ManufacturerGTE applies the GTE predicate on the "manufacturer" field.
func ManufacturerGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldManufacturer, v))
}

// ManufacturerLT applies the LT predicate on the "manufacturer" field.
func ManufacturerLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldManufacturer, v))
}

// ManufacturerLTE applies the LTE predicate on the "manufacturer" field.
func ManufacturerLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldManufacturer, v))
}

// ManufacturerContains applies the Contains predicate on the "manufacturer" field.
func ManufacturerContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldManufacturer, v))
}

// ManufacturerHasPrefix applies the HasPrefix predicate on the "manufacturer" field.
func ManufacturerHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldManufacturer, v))
}

// ManufacturerHasSuffix applies the HasSuffix predicate on the "manufacturer" field.
func ManufacturerHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldManufacturer, v))
}

// ManufacturerEqualFold applies the EqualFold predicate on the "manufacturer" field.
func ManufacturerEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldManufacturer, v))
}

// ManufacturerContainsFold applies the ContainsFold predicate on the "manufacturer" field.
func ManufacturerContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldManufacturer, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Assets {
	return predicate.Assets(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Assets {
	return predicate.Assets(sql.FieldContainsFold(FieldModel, v))
}

// OtherMetadataIsNil applies the IsNil predicate on the "other_metadata" field.
func OtherMetadataIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldOtherMetadata))
}

// OtherMetadataNotNil applies the NotNil predicate on the "other_metadata" field.
func OtherMetadataNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldOtherMetadata))
}

// AssetTypeIDEQ applies the EQ predicate on the "asset_type_id" field.
func AssetTypeIDEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetTypeID, v))
}

// AssetTypeIDNEQ applies the NEQ predicate on the "asset_type_id" field.
func AssetTypeIDNEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetTypeID, v))
}

// AssetTypeIDIn applies the In predicate on the "asset_type_id" field.
func AssetTypeIDIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetTypeID, vs...))
}

// AssetTypeIDNotIn applies the NotIn predicate on the "asset_type_id" field.
func AssetTypeIDNotIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetTypeID, vs...))
}

// AssetTypeIDIsNil applies the IsNil predicate on the "asset_type_id" field.
func AssetTypeIDIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldAssetTypeID))
}

// AssetTypeIDNotNil applies the NotNil predicate on the "asset_type_id" field.
func AssetTypeIDNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldAssetTypeID))
}

// AssetCategoryIDEQ applies the EQ predicate on the "asset_category_id" field.
func AssetCategoryIDEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldAssetCategoryID, v))
}

// AssetCategoryIDNEQ applies the NEQ predicate on the "asset_category_id" field.
func AssetCategoryIDNEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldAssetCategoryID, v))
}

// AssetCategoryIDIn applies the In predicate on the "asset_category_id" field.
func AssetCategoryIDIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldAssetCategoryID, vs...))
}

// AssetCategoryIDNotIn applies the NotIn predicate on the "asset_category_id" field.
func AssetCategoryIDNotIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldAssetCategoryID, vs...))
}

// AssetCategoryIDIsNil applies the IsNil predicate on the "asset_category_id" field.
func AssetCategoryIDIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldAssetCategoryID))
}

// AssetCategoryIDNotNil applies the NotNil predicate on the "asset_category_id" field.
func AssetCategoryIDNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldAssetCategoryID))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDIsNil applies the IsNil predicate on the "organization_id" field.
func OrganizationIDIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldOrganizationID))
}

// OrganizationIDNotNil applies the NotNil predicate on the "organization_id" field.
func OrganizationIDNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldOrganizationID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Assets {
	return predicate.Assets(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Assets {
	return predicate.Assets(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Assets {
	return predicate.Assets(sql.FieldNotNull(FieldUpdatedAt))
}

// HasAssetCategory applies the HasEdge predicate on the "asset_category" edge.
func HasAssetCategory() predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssetCategoryTable, AssetCategoryColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetCategory
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetCategoryWith applies the HasEdge predicate on the "asset_category" edge with a given conditions (other predicates).
func HasAssetCategoryWith(preds ...predicate.AssetCategory) predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := newAssetCategoryStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetCategory
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssetType applies the HasEdge predicate on the "asset_type" edge.
func HasAssetType() predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssetTypeTable, AssetTypeColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetType
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetTypeWith applies the HasEdge predicate on the "asset_type" edge with a given conditions (other predicates).
func HasAssetTypeWith(preds ...predicate.AssetType) predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := newAssetTypeStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.AssetType
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Organization
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Assets {
	return predicate.Assets(func(s *sql.Selector) {
		step := newOrganizationStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Organization
		step.Edge.Schema = schemaConfig.Assets
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Assets) predicate.Assets {
	return predicate.Assets(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Assets) predicate.Assets {
	return predicate.Assets(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Assets) predicate.Assets {
	return predicate.Assets(sql.NotPredicates(p))
}
