// Code generated by ent, DO NOT EDIT.

package procurementfraudrisk

import (
	"moon/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldID, id))
}

// ProcurementPlanID applies equality check predicate on the "procurement_plan_id" field. It's identical to ProcurementPlanIDEQ.
func ProcurementPlanID(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldProcurementPlanID, v))
}

// ProcurementImplementationID applies equality check predicate on the "procurement_implementation_id" field. It's identical to ProcurementImplementationIDEQ.
func ProcurementImplementationID(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldProcurementImplementationID, v))
}

// RiskLevel applies equality check predicate on the "risk_level" field. It's identical to RiskLevelEQ.
func RiskLevel(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskLevel, v))
}

// RiskReason applies equality check predicate on the "risk_reason" field. It's identical to RiskReasonEQ.
func RiskReason(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskReason, v))
}

// RiskScore applies equality check predicate on the "risk_score" field. It's identical to RiskScoreEQ.
func RiskScore(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldCreatedAt, v))
}

// ProcurementPlanIDEQ applies the EQ predicate on the "procurement_plan_id" field.
func ProcurementPlanIDEQ(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldProcurementPlanID, v))
}

// ProcurementPlanIDNEQ applies the NEQ predicate on the "procurement_plan_id" field.
func ProcurementPlanIDNEQ(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldProcurementPlanID, v))
}

// ProcurementPlanIDIn applies the In predicate on the "procurement_plan_id" field.
func ProcurementPlanIDIn(vs ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldProcurementPlanID, vs...))
}

// ProcurementPlanIDNotIn applies the NotIn predicate on the "procurement_plan_id" field.
func ProcurementPlanIDNotIn(vs ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldProcurementPlanID, vs...))
}

// ProcurementPlanIDGT applies the GT predicate on the "procurement_plan_id" field.
func ProcurementPlanIDGT(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldProcurementPlanID, v))
}

// ProcurementPlanIDGTE applies the GTE predicate on the "procurement_plan_id" field.
func ProcurementPlanIDGTE(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldProcurementPlanID, v))
}

// ProcurementPlanIDLT applies the LT predicate on the "procurement_plan_id" field.
func ProcurementPlanIDLT(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldProcurementPlanID, v))
}

// ProcurementPlanIDLTE applies the LTE predicate on the "procurement_plan_id" field.
func ProcurementPlanIDLTE(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldProcurementPlanID, v))
}

// ProcurementPlanIDIsNil applies the IsNil predicate on the "procurement_plan_id" field.
func ProcurementPlanIDIsNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIsNull(FieldProcurementPlanID))
}

// ProcurementPlanIDNotNil applies the NotNil predicate on the "procurement_plan_id" field.
func ProcurementPlanIDNotNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotNull(FieldProcurementPlanID))
}

// ProcurementImplementationIDEQ applies the EQ predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDEQ(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDNEQ applies the NEQ predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDNEQ(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDIn applies the In predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDIn(vs ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldProcurementImplementationID, vs...))
}

// ProcurementImplementationIDNotIn applies the NotIn predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDNotIn(vs ...uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldProcurementImplementationID, vs...))
}

// ProcurementImplementationIDGT applies the GT predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDGT(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDGTE applies the GTE predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDGTE(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDLT applies the LT predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDLT(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDLTE applies the LTE predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDLTE(v uuid.UUID) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldProcurementImplementationID, v))
}

// ProcurementImplementationIDIsNil applies the IsNil predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDIsNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIsNull(FieldProcurementImplementationID))
}

// ProcurementImplementationIDNotNil applies the NotNil predicate on the "procurement_implementation_id" field.
func ProcurementImplementationIDNotNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotNull(FieldProcurementImplementationID))
}

// RiskLevelEQ applies the EQ predicate on the "risk_level" field.
func RiskLevelEQ(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskLevel, v))
}

// RiskLevelNEQ applies the NEQ predicate on the "risk_level" field.
func RiskLevelNEQ(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldRiskLevel, v))
}

// RiskLevelIn applies the In predicate on the "risk_level" field.
func RiskLevelIn(vs ...string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldRiskLevel, vs...))
}

// RiskLevelNotIn applies the NotIn predicate on the "risk_level" field.
func RiskLevelNotIn(vs ...string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldRiskLevel, vs...))
}

// RiskLevelGT applies the GT predicate on the "risk_level" field.
func RiskLevelGT(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldRiskLevel, v))
}

// RiskLevelGTE applies the GTE predicate on the "risk_level" field.
func RiskLevelGTE(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldRiskLevel, v))
}

// RiskLevelLT applies the LT predicate on the "risk_level" field.
func RiskLevelLT(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldRiskLevel, v))
}

// RiskLevelLTE applies the LTE predicate on the "risk_level" field.
func RiskLevelLTE(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldRiskLevel, v))
}

// RiskLevelContains applies the Contains predicate on the "risk_level" field.
func RiskLevelContains(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldContains(FieldRiskLevel, v))
}

// RiskLevelHasPrefix applies the HasPrefix predicate on the "risk_level" field.
func RiskLevelHasPrefix(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldHasPrefix(FieldRiskLevel, v))
}

// RiskLevelHasSuffix applies the HasSuffix predicate on the "risk_level" field.
func RiskLevelHasSuffix(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldHasSuffix(FieldRiskLevel, v))
}

// RiskLevelEqualFold applies the EqualFold predicate on the "risk_level" field.
func RiskLevelEqualFold(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEqualFold(FieldRiskLevel, v))
}

// RiskLevelContainsFold applies the ContainsFold predicate on the "risk_level" field.
func RiskLevelContainsFold(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldContainsFold(FieldRiskLevel, v))
}

// RiskReasonEQ applies the EQ predicate on the "risk_reason" field.
func RiskReasonEQ(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskReason, v))
}

// RiskReasonNEQ applies the NEQ predicate on the "risk_reason" field.
func RiskReasonNEQ(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldRiskReason, v))
}

// RiskReasonIn applies the In predicate on the "risk_reason" field.
func RiskReasonIn(vs ...string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldRiskReason, vs...))
}

// RiskReasonNotIn applies the NotIn predicate on the "risk_reason" field.
func RiskReasonNotIn(vs ...string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldRiskReason, vs...))
}

// RiskReasonGT applies the GT predicate on the "risk_reason" field.
func RiskReasonGT(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldRiskReason, v))
}

// RiskReasonGTE applies the GTE predicate on the "risk_reason" field.
func RiskReasonGTE(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldRiskReason, v))
}

// RiskReasonLT applies the LT predicate on the "risk_reason" field.
func RiskReasonLT(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldRiskReason, v))
}

// RiskReasonLTE applies the LTE predicate on the "risk_reason" field.
func RiskReasonLTE(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldRiskReason, v))
}

// RiskReasonContains applies the Contains predicate on the "risk_reason" field.
func RiskReasonContains(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldContains(FieldRiskReason, v))
}

// RiskReasonHasPrefix applies the HasPrefix predicate on the "risk_reason" field.
func RiskReasonHasPrefix(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldHasPrefix(FieldRiskReason, v))
}

// RiskReasonHasSuffix applies the HasSuffix predicate on the "risk_reason" field.
func RiskReasonHasSuffix(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldHasSuffix(FieldRiskReason, v))
}

// RiskReasonIsNil applies the IsNil predicate on the "risk_reason" field.
func RiskReasonIsNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIsNull(FieldRiskReason))
}

// RiskReasonNotNil applies the NotNil predicate on the "risk_reason" field.
func RiskReasonNotNil() predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotNull(FieldRiskReason))
}

// RiskReasonEqualFold applies the EqualFold predicate on the "risk_reason" field.
func RiskReasonEqualFold(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEqualFold(FieldRiskReason, v))
}

// RiskReasonContainsFold applies the ContainsFold predicate on the "risk_reason" field.
func RiskReasonContainsFold(v string) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldContainsFold(FieldRiskReason, v))
}

// RiskScoreEQ applies the EQ predicate on the "risk_score" field.
func RiskScoreEQ(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldRiskScore, v))
}

// RiskScoreNEQ applies the NEQ predicate on the "risk_score" field.
func RiskScoreNEQ(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldRiskScore, v))
}

// RiskScoreIn applies the In predicate on the "risk_score" field.
func RiskScoreIn(vs ...int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldRiskScore, vs...))
}

// RiskScoreNotIn applies the NotIn predicate on the "risk_score" field.
func RiskScoreNotIn(vs ...int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldRiskScore, vs...))
}

// RiskScoreGT applies the GT predicate on the "risk_score" field.
func RiskScoreGT(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldRiskScore, v))
}

// RiskScoreGTE applies the GTE predicate on the "risk_score" field.
func RiskScoreGTE(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldRiskScore, v))
}

// RiskScoreLT applies the LT predicate on the "risk_score" field.
func RiskScoreLT(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldRiskScore, v))
}

// RiskScoreLTE applies the LTE predicate on the "risk_score" field.
func RiskScoreLTE(v int) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldRiskScore, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProcurementFraudRisk) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProcurementFraudRisk) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProcurementFraudRisk) predicate.ProcurementFraudRisk {
	return predicate.ProcurementFraudRisk(sql.NotPredicates(p))
}
